### PR TITLE
Fix doc issue where parameters listed twice in description

### PR DESCRIPTION
**Pull request by lorenzncode**
Fix doc issue where parameters could be listed twice in the method description

* Remove sphinx extension sphinx_autodoc_typehints

* Update sphinx pin to version 4.2.0

* Show typehints in both signature and description

### CODE REVIEW

**Comment by lorenzncode** [comment]
To resolve #819.

**Comment by adam-urbanczyk** [comment]
Looks good @lorenzncode . One minor point - would it be easy to move self to the top?

tmp

**Comment by lorenzncode** [comment]
Yes, it's easy to move self to the top.  I'll update the PR shortly.

**Comment by lorenzncode** [comment]
I see one open issue to debug - the methods with Literal in the signature are rendered with strikethrough:

image

I also clobbered the existing setup() function that adds tables.css.

**Comment by lorenzncode** [comment]
With docutils 0.16, the result is as expected:
image



Prior result with strikethrough text was using docutils  0.17.1.  HTML is ```<s><span class="pre">'XY'</span></s>```

Perhaps related to https://docutils.sourceforge.io/HISTORY.html

`Use HTML text-level tags <small>, <s>, <q>, <dfn>, <var>, <samp>, <kbd>, <i>, <b>, <u>, <mark>, and <bdi> if a unique, matching class value is found in inline and literal elements. Use <ins> and <del> if a unique matching class value is found in inline, literal, or container elements. Use <small> for generated code line numbers.`

**Comment by lorenzncode** [comment]
The html (strikethrough) issue was reported by another user as sphinx-doc/sphinx#9872.  I will update this PR after sphinx 4.3.1 is released.

**Review by adam-urbanczyk — APPROVED** [review]

**Comment by adam-urbanczyk** [comment]
Shall I merge or wait for 4.3.1 @lorenzncode ?

**Comment by lorenzncode** [comment]
I'd propose to wait for sphinx 4.3.1.  I expect the release soon based on comments in the GH issues and the sphinx 4.3.1 release milestone tracker.  I'll watch for the release then update this PR to pin to sphinx 4.3.1.

**Comment by lorenzncode** [comment]
Sphinx 4.3.1 is out!  The docs look good to me now (other than the known docstring issues mentioned in #922 to be fixed separately).

**Comment by jmwright** [comment]
Looks like there's [a glibc error](https://dev.azure.com/cadquery/conda-packages/_build/results?buildId=2002&view=logs&j=469eeba9-e84c-576c-2174-efb2c0654ac2&t=a31fa24d-b17a-5ff4-3b81-3d95ffba7ac2&l=554) with Python 3.9 in Azure's Linux runs.

**Comment by adam-urbanczyk** [comment]
Yup, will look into this

**Comment by lorenzncode** [comment]
- [ ] Update sphinx pin to version 4.4.0
- [ ] Test with new _autodoc_typehints_format_ setting; compare 'fully-qualified' vs 'short'

I'd like to complete the tasks above before this is merged.

**Comment by lorenzncode** [comment]
This could be a good time for this PR as it will resolve the current Read the Docs build failures (for example see PR #1018).

**Comment by jmwright** [comment]
@lorenzncode Sounds good. It has two approvals, so I think it is ready to merge. Do you want to do the honors?

**Comment by jmwright** [comment]
Thanks for fixing this @lorenzncode

**Pull request merged**
