### PR TITLE
Bump docs version to 2.2.0

### LINKED ISSUE #1283: Update version in Sphinx `conf.py`
The version and release used by Sphinx is set to `1.0` and `1.0.0` respectively.

Update to reflect that the docs are for CadQuery 2.

```python
# doc/conf.py

# The short X.Y version.
version = "1.0"
# The full version, including alpha/beta/rc tags.
release = "1.0.0"
```

One place I have seen this version used is links generated with [sphinx.ext.intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html). The intersphinx link title is set to "(in CadQuery v1.0)" and is displayed on hover.

### PR DESCRIPTION
**Pull request by sethfischer**
Closes #1283

### CODE REVIEW

**Comment by jmwright** [comment]
@sethfischer Should the X.Y version be `2.0` or `2.2`?

**Comment by sethfischer** [comment]
@jmwright, yes X.Y version should have been "2.2". Fixed.

**Comment by lorenzncode** [comment]
The 2.2.0 docs have already been built -  I think this is what you see with version `stable`.  

Rather than hardcode the version for version `latest`, perhaps the version can be set automatically based on the more straightforward versioning to be defined in #1286.

**Comment by adam-urbanczyk** [comment]
@lorenzncode @jmwright shall I just merge this PR?

**Comment by jmwright** [comment]
+1 to merge

**Comment by lorenzncode** [comment]
> @lorenzncode @jmwright shall I just merge this PR?

Yes, please do.

**Pull request merged**
