### PR TITLE
Use pytest in azure as well

### LINKED ISSUE #238: #236 broke the azure pipeline
Need to update the conda recipe to run tests differently

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Will resolve #238 .

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
It works locally. Could you take a look @jmwright once CI passes ?

**Comment by jmwright** [comment]
@adam-urbanczyk CircleCI still shows failing for some reason.

**Comment by jmwright** [comment]
```
No file to run: 'runtests.py'
```
I'm guessing that the cadquery repo needs to be cloned in addition to being installed via conda or pip to get the runtests.py script since it's in the top level directory?

**Comment by adam-urbanczyk** [comment]
@jmwright  I removed circleci config - it is redundant (MacOS is tested with travis).

**Comment by adam-urbanczyk** [comment]
Alright, let's get rid of the red badge then.

**Pull request merged**
