### PR TITLE
Revise README Contributing Code

### PR DESCRIPTION
**Pull request by winksaville**
Fixes 403

### CODE REVIEW

**Comment by winksaville** [comment]
@adam-urbanczyk, these new instructions work for me. If you have another technique, let me know and I'll change this.

**Comment by adam-urbanczyk** [comment]
Why not the `pip install -e` version? Feels less hacky to me.

**Comment by winksaville** [comment]
I agree, what I've got is a hack and to Linux oriented. But I tried using
pip before and it didn't work, the dependencies weren't installed, IIRC.

Could you provide the list of commands needed between "Fork the CadQuery
repository." and "Start with the tests!".

**Comment by adam-urbanczyk** [comment]
This works for me:
```
git clone https://github.com/CadQuery/cadquery.git
cd cadquery
conda env create environment.yaml
conda activate cadquery
conda install -c cadquery -c conda-forge cq-editor #if desired
pip install -e .
```
NB: last line installs the cloned repo in an editable mode.

**Comment by winksaville** [comment]
@adam-urbanczyk, I've pushed a revised version that uses `pip install -e .`, thanks!

**Comment by adam-urbanczyk** [comment]
Looks good, thanks for the contribution @winksaville .

**Pull request merged**
