### PR TITLE
Fix empty render in docs and doc build error

### LINKED ISSUE #1364: FixedAxis assembly constraint VTK render is broken
See https://cadquery.readthedocs.io/en/latest/assy.html#fixedaxis

The VTK render window is blank and directive `.. cadquery::` fails with:

```commandline
$ rm -r target/docs/ && ./build-docs.sh
Running Sphinx v5.3.0
⋮
updating environment: [new config] 17 added, 0 changed, 0 removed
Traceback (most recent call last):                                                                                                                                                                  
  File "...cadquery/cadquery/cqgi.py", line 564, in visit_Assign
    for n, v in zip(left_side.elts, node.value.elts):
AttributeError: 'Name' object has no attribute 'elts'
Unable to handle assignment for node 'Name(id='pnt', ctx=Store())'
reading sources... [100%] sketch                                                                                                                                                                    
⋮
build succeeded.

The HTML pages are in ../target/docs.
```

### PR DESCRIPTION
**Pull request by lorenzncode**
Closes #1364

### CODE REVIEW

**Comment by lorenzncode** [comment]
I'll revert to the previous version of the assembly doc example.  To avoid the cqgi error, the unsupported parameter type can be skipped.  Perhaps with a future enhancement cqgi can support additional parameter types.

**Review by jmwright — APPROVED** [review]
Looks good, thanks @lorenzncode 

Should we create an issue for adding tuple support to CQGI?

**Comment by lorenzncode** [comment]
> Should we create an issue for adding tuple support to CQGI?

Done, opened #1370

**Review by adam-urbanczyk — APPROVED** [review]

**Comment by adam-urbanczyk** [comment]
Thanks @lorenzncode !

**Pull request merged**
