### PR TITLE
Faster makeFromWires

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Related to #766

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
I see quite significant (10x) speedup with this PR. We could make this roughly 2x faster, but that would require many more changes.

**Comment by marcus7070** [comment]
Wow, this code:
```python
import cadquery as cq
from itertools import product

num = 49
hole_dim = 1
wall_thick = 0.2
outer_dim = num * hole_dim + (num + 1) * wall_thick

vals = [wall_thick + (hole_dim + wall_thick) * idx for idx in range(num)]
points = [(x, y) for x, y in product(vals, repeat=2)]

grid = (
    cq.Workplane()
    .rect(outer_dim, outer_dim, centered=False)
    .pushPoints(points)
    .rect(hole_dim, hole_dim, centered=False)
    .extrude(2)
)
```
went from 111 seconds down to 4.4s. That's fantastic, thanks very much @adam-urbanczyk!

**Review by marcus7070 — APPROVED** [review]
I've rendered a bunch of my models with this code now and nothing has broken, looks great to me!

**Review by jmwright — APPROVED** [review]
Looks good. Thanks a lot @adam-urbanczyk ! This yields incredible improvements.

**Pull request merged**
