### PR TITLE
Testing newer version of pythonOCC

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Trying out latest pythonOCC version.

WIP do not merge

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
Thanks, I'll try to reproduce locally and go from there.

**Comment by adam-urbanczyk** [comment]
It happens here: https://github.com/CadQuery/cadquery/blob/b9685f4b6aba7be9759afc02fa9b886cdac0f405/cadquery/occ_impl/exporters.py#L315

If I modify this function and simply return empty string from  all but two tests run OK.

**Comment by adam-urbanczyk** [comment]
More testing needed but this PR should work with https://github.com/tpaviot/pythonocc-core/pull/605

**Comment by adam-urbanczyk** [comment]
I made quite some progress on this. Windows and linux work (NB: only python 3 will be supported - is everyone aware?). MacOS gives me a weird crash:
```
(lldb) target create --core "/cores/core.3347"
warning: (x86_64) /cores/core.3347 load command 1045 LC_SEGMENT_64 has a fileoff + filesize (0x56e56000) that extends beyond the end of the file (0x56e55000), the segment will be truncated to match
warning: (x86_64) /cores/core.3347 load command 1046 LC_SEGMENT_64 has a fileoff (0x56e56000) that extends beyond the end of the file (0x56e55000), ignoring this section
Core file '/cores/core.3347' (x86_64) was loaded.
(lldb) bt
* thread #1, stop reason = signal SIGSTOP
  * frame #0: 0x000000010aca02a4 libTKG2d.11.dylib`Geom2d_BSplineCurve::Degree() const + 4
    frame #1: 0x000000010a70d51a libTKGeomBase.11.dylib`ProjLib_ProjectedCurve::Load(Handle_Adaptor3d_HCurve const&) + 5562
    frame #2: 0x000000010a70e1af libTKGeomBase.11.dylib`ProjLib_ProjectedCurve::ProjLib_ProjectedCurve(Handle_Adaptor3d_HSurface const&, Handle_Adaptor3d_HCurve const&, double) + 111
    frame #3: 0x000000010a711f42 libTKGeomBase.11.dylib`GeomProjLib::Curve2d(Handle_Geom_Curve const&, double, double, Handle_Geom_Surface const&, double, double, double, double, double&) + 482
    frame #4: 0x000000010a19d716 libTKGeomAlgo.11.dylib`GeomInt_IntSS::BuildPCurves(double, double, double&, Handle_Geom_Surface const&, Handle_Geom_Curve const&, Handle_Geom2d_Curve&) + 198
    frame #5: 0x00000001099cd80d libTKBO.11.dylib`IntTools_FaceFace::MakeCurve(int, Handle_Adaptor3d_TopolTool const&, Handle_Adaptor3d_TopolTool const&) + 21949
    frame #6: 0x00000001099c6803 libTKBO.11.dylib`IntTools_FaceFace::Perform(TopoDS_Face const&, TopoDS_Face const&) + 7123
    frame #7: 0x0000000109a589d5 libTKBO.11.dylib`void OSD_Parallel::For<BOPCol_Functor<BOPAlgo_FaceFace, BOPCol_NCVector<BOPAlgo_FaceFace> > >(int, int, BOPCol_Functor<BOPAlgo_FaceFace, BOPCol_NCVector<BOPAlgo_FaceFace> > const&, bool) + 117
    frame #8: 0x0000000109a4ce4e libTKBO.11.dylib`BOPAlgo_PaveFiller::PerformFF() + 1694
    frame #9: 0x0000000109a3894d libTKBO.11.dylib`BOPAlgo_PaveFiller::PerformInternal() + 173
    frame #10: 0x0000000109a38755 libTKBO.11.dylib`BOPAlgo_PaveFiller::Perform() + 117
    frame #11: 0x00000001099e3da2 libTKBO.11.dylib`BRepAlgoAPI_BooleanOperation::Build() + 450
    frame #12: 0x00000001099e7556 libTKBO.11.dylib`BRepAlgoAPI_Cut::BRepAlgoAPI_Cut(TopoDS_Shape const&, TopoDS_Shape const&) + 38
    frame #13: 0x000000010f4ad1a2 _BRepAlgoAPI.so`_wrap_new_BRepAlgoAPI_Cut__SWIG_2(_object*, int, _object**) + 254
    frame #14: 0x000000010f4a58bb _BRepAlgoAPI.so`_wrap_new_BRepAlgoAPI_Cut(_object*, _object*) + 114
    frame #15: 0x0000000107ae163d libpython3.6m.dylib`PyCFunction_Call + 205
```
@jmwright @dcowden  any ideas? `Geom2d_BSplineCurve::Degree()` looks like a simple property getter. Does anyone of you have the ability (and will) to debug this on a Mac?

**Comment by jmwright** [comment]
@adam-urbanczyk I'm trying to debug this on MacOS. I installed everything in the base conda environment, started Python, then imported CadQuery, and didn't get any errors. Does that error only happen when running the tests? I ran the tests on the master branch locally. I don't see that error, only this one:
```
 Step File Name : /var/folders/14/wskrdq1104d24_lbzy_mb_5c0000gp/T/testWorkplaneOnExistingSolid.step(530 ents)  Write  Done
....Error Executing Script:
Traceback (most recent call last):
  File "/Users/Cathy/Downloads/cadquery/cadquery/cqgi.py", line 112, in build
    exec(c, env)
  File "<cqscript>", line 2, in <module>
ValueError: ERROR
Full Text of Script:

raise ValueError("ERROR")

.Unable to handle function call
.Adding Parameter name=a, desc=FirstLetter
...Error Executing Script:
Traceback (most recent call last):
  File "/Users/Cathy/Downloads/cadquery/cadquery/cqgi.py", line 264, in set_value
    f = float(new_value)
ValueError: could not convert string to float: 'a string'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Cathy/Downloads/cadquery/cadquery/cqgi.py", line 103, in build
    self.set_param_values(build_parameters)
  File "/Users/Cathy/Downloads/cadquery/cadquery/cqgi.py", line 139, in set_param_values
    p.set_value(v)
  File "/Users/Cathy/Downloads/cadquery/cadquery/cqgi.py", line 269, in set_value
    .format(str(new_value), self.name))
cadquery.cqgi.InvalidParameterError: Cannot set value 'a string' for parameter 'h': parameter must be numeric.
Full Text of Script:

h = 20.0
build_object(h)

.Error Executing Script:
Traceback (most recent call last):
  File "/Users/Cathy/Downloads/cadquery/cadquery/cqgi.py", line 103, in build
    self.set_param_values(build_parameters)
  File "/Users/Cathy/Downloads/cadquery/cadquery/cqgi.py", line 136, in set_param_values
    "Cannot set value '%s': not a parameter of the model." % k)
cadquery.cqgi.InvalidParameterError: Cannot set value 'w': not a parameter of the model.
Full Text of Script:

h = 20.0
build_object(h)

..Unable to handle function call
..Error Executing Script:
Traceback (most recent call last):
  File "/Users/Cathy/Downloads/cadquery/cadquery/cqgi.py", line 118, in build
    "Script did not call build_object-- no output available.")
cadquery.cqgi.NoOutputError: Script did not call build_object-- no output available.
Full Text of Script:

h = 20.0
```

**Comment by jmwright** [comment]
@adam-urbanczyk I set up a conda environment for CadQuery, did the install via the readme, then removed the cadquery-occ package using conda, then installed the adam-urbanczyk-OCC-version-update branch using pip (`pip install git+https://github.com/CadQuery/cadquery.git@adam-urbanczyk-OCC-version-update`). I get an error that OCC.Core is missing. Is there a better way for me to try the branch than installing it using pip?
```
$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cadquery as cq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/User1/miniconda3/envs/cadquery/lib/python3.6/site-packages/cadquery/__init__.py", line 2, in <module>
    from .occ_impl.geom import Plane, BoundBox, Vector, Matrix
  File "/Users/User1/miniconda3/envs/cadquery/lib/python3.6/site-packages/cadquery/occ_impl/geom.py", line 4, in <module>
    from OCC.Core.gp import gp_Vec, gp_Ax1, gp_Ax3, gp_Pnt, gp_Dir, gp_Trsf, gp, gp_XYZ
ModuleNotFoundError: No module named 'OCC.Core'
```

**Comment by jmwright** [comment]
Ok, there was an [API change](https://github.com/tpaviot/pythonocc-core/issues/565) in PythonOCC from `OCC.Whatever` to `OCC.Core.Whatever`. I've tried running the newer version of PythonOCC from the CadQuery channel, but am not having much luck. The version that was linked on this [CQ-editor issue](https://github.com/CadQuery/CQ-editor/issues/7#issuecomment-455817605) seems to be unavailable now.

**Comment by jmwright** [comment]
Maybe the lack of OCC.Vizualization is related to [this issue](https://github.com/tpaviot/pythonocc-core/issues/484)?

**Comment by jmwright** [comment]
Ok, it looks like I have a working environment. For some reason it won't work when I install the update branch using pip.

**Comment by jmwright** [comment]
[This is the line](https://github.com/CadQuery/cadquery/blob/5fb7fa8354f081639d711b659fd1b61fcfe1b879/tests/TestCadQuery.py#L836) that the OSX environment appears to segfault on in Travis. A triangular prism is being exported. I'll try to run the test suite with the same environment on a MacBook.

**Comment by adam-urbanczyk** [comment]
@jmwright sorry I missed your questions. Looking forward to your results. Do you have experience with CircleCI BTW? I see there is a possibility of SSHing into the virtual machine.

**Comment by jmwright** [comment]
> Do you have experience with CircleCI BTW?

Unfortunately, no. I always use Travis and AppVeyor.

The test suite on the MacBook run to the same test, hangs for awhile, and then segfaults. Is it possible it's a tessellation precision problem and the process is running out of memory?

I need to separate that code out into its own script and run a debugger against it. @adam-urbanczyk I don't have a lot of experience running debuggers against Python, so if you've got any tips I'm open to hearing them.

**Comment by jmwright** [comment]
I separated the segfaulting code out into a separate script, and ran pdb on it, but I didn't get any more information than I had before.

**Comment by adam-urbanczyk** [comment]
I found a similar issues in the OCCT bug tracker. Advised workaround was to use `-O1` optimization on Mac.

**Comment by jmwright** [comment]
@adam-urbanczyk is that optimization applied during compilation?

**Comment by adam-urbanczyk** [comment]
@jmwright  yes indeed. In the end I changed two things:
* oce 0.18.2 i.s.o. 0.18.3 
*  `-O1` compilation flag on Linux and Mac (on Linux because it is defined in one file for both systems). 
I don't know which of the two things solved it, but I'd like to merge and move forward with new features. 

@dcowden @jmwright merging this will mean that we do not support python 2.7 anymore. It will be EOL in ~10 monts (cf. https://pythonclock.org/) so if think the timing is quite good. Any thoughts?

**Comment by jmwright** [comment]
@adam-urbanczyk I've been following all the commits on this and I say go ahead and merge. If anyone really needs Python 2.7 and/or FreeCAD support, they can use dcowden/cadquery still. I'm hoping that we can add FreeCAD export at some point, but that's another issue.

Thanks for all your work on this!

**Comment by adam-urbanczyk** [comment]
@dcowden what are your thoughts? I'd like to have buy-in from everyone.

**Comment by adam-urbanczyk** [comment]
OK merging. I want to move forward...

**Pull request merged**
