### PR TITLE
Revamping Cheatsheet

### PR DESCRIPTION
**Pull request by jpoles1**
This PR includes a revamped cheatsheet. It includes more information on the most common commands. Some commands have been excluded from this first draft at rewriting the cheatsheet, any important ones I missed can certainly be added, just let me know.  Addresses issue #1128.

I've also made some changes to the README to link to the documentation more clearly under the "Getting Started" header, including a link to the cheatsheet.

Finally, made a few stylistic fixes to that part of the README, added a link to a VSCode extension. This part is more optional, but figured I'd include it, no worries if we need to drop it.

### CODE REVIEW

**Comment by jpoles1** [comment]
Quick preview for anyone interested, while we wait for PR!

https://4k6570.csb.app/

**Comment by jmwright** [comment]
@jpoles1 Thanks for putting this together. It might just be because I'm on mobile, but the border goes all the way around some tables, but not others.

Screenshot_20220728-220257-827

**Comment by jpoles1** [comment]
@jmwright yea, that's a problem on mobile specifically that I'm aware of, will try and fix soon!

**Comment by jmwright** [comment]
It looks like this is ready for review. Do you agree @jpoles1 ?

**Comment by jpoles1** [comment]
@jmwright, I think it might benefit from adding a few more key commands before final review. Also potentially a few more of the key params for commonly used functions. Might solicit some feedback from the discord crew, and then request final review!

**Comment by jpoles1** [comment]
Still working on tuning this resource, and I think making some nice improvements! I think this latest version will be well optimized for a variety of different screen sizes. I've also started to add some fancier functionality, like the all-important "dark mode"! 
https://jpoles1.github.io/CadQuery-Cheatsheet/

I thinking I want to keep going with incremental development in this separate repo for now, and potentially merge back in down the line once I feel it's adequately polished. Open to suggestions, of course! I think I may close this PR for now and re-open in the future?

**Comment by jmwright** [comment]
@jpoles1 It looks good so far. If you would rather wait to merge that's fine, but what you have is already an improvement over what exists right now. I see that it has embedded Javascript to toggle the light/dark mode. Will the cheatsheet fail to load if someone has Javascript disabled for some reason?

**Comment by jpoles1** [comment]
Hey @jmwright , apologies for the hiatus, work's been keeping me busy. I've been using the cheatsheet on and off while working on CadQuery projects, and I'm pretty happy with how it's looking for now!

None of the page should require JS, it's only there for switching between day + night mode. I tested disabing JS and confirmed it works just fine!

What do you think is the best way to move forward: 
1) Leave it hosted on my repo and simply link to it from the docs/readme. 
2) should I merge the code into the repo, so it'd theoretically appear [here](https://cadquery.readthedocs.io/en/latest/_static/cadquery_cheatsheet.html)? Not sure when/how often the readthedocs is updated/regenerated.

(I've maintained it as a single page html file, similar to the old version).  

In either case, I'd also like to make a link to the Cheatsheet near the top of the readme for easy access (not sure exactly where). I was thinking of a small little section (maybe right underneath the badges) for quick access to the most important links out (Docs/Cheatsheet/Discord/etc). 

Also, would it be ok to add a quick link to the cheatsheet to the sidebar in the [ReadTheDocs](https://cadquery.readthedocs.io/en/latest/index.html)? Perhaps right under the [CadQuery Examples](https://cadquery.readthedocs.io/en/latest/examples.html#id1) sidebar link?

**Comment by jmwright** [comment]
> What do you think is the best way to move forward:

ReadTheDocs should be updated whenever we push to the main branch of the repo, so your cheatsheet should go live soon after this PR is merged. I think ReadTheDocs would be the most stable place to link to from the readme.

> I was thinking of a small little section (maybe right underneath the badges) for quick access to the most important links out (Docs/Cheatsheet/Discord/etc).

A quick links section at the top of the readme sounds like a good idea to me. You might want to include a link for the Google Group too for those who don't use Discord.

> Also, would it be ok to add a quick link to the cheatsheet to the sidebar in the [ReadTheDocs](https://cadquery.readthedocs.io/en/latest/index.html)? Perhaps right under the [CadQuery Examples](https://cadquery.readthedocs.io/en/latest/examples.html#id1) sidebar link?

I think a cheatsheet link in the sidebar on ReadTheDocs would be fine.

**Comment by jpoles1** [comment]
Alright, I think it's all set! So to summarize:
1) Revamps cheatsheet
2) Adds links quickbar to top of readme
3) Adds link to cheatsheet from docs

Please let me know if any issues I need to correct, thanks!

**Comment by jmwright** [comment]
@jpoles1 Why was [this CQ-editor section](https://github.com/CadQuery/cadquery/pull/1129/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L118) removed?

**Comment by jpoles1** [comment]
@jmwright agh, I think I messed that up in the merge. I had moved it up the readme earlier and then there were edits made in the mean time which have made a mess of it. Lemme try and figure out how to remove that from the PR...

**Comment by jpoles1** [comment]
I think that should fix it... let me know if I mixed up anything else, my apologies.

**Comment by jmwright** [comment]
@roipoussiere Am I understanding correctly that cadquery-server has replaced the VSCode extension that you created? So should the link [here](https://github.com/CadQuery/cadquery/pull/1129/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R51) point to cadquery-server's [VSCode instructions](https://github.com/roipoussiere/cadquery-server#integration-with-vscode) instead?

@jpoles1 I was just about to recommend merging this, but then the question above occurred to me. I think your changes look good though, and we can move forward on merging once the VSCode extension question is resolved.

@adam-urbanczyk @lorenzncode How does this PR look to you two?

**Comment by roipoussiere** [comment]
@jmwright I had this in mind but in fact I decided to continue to maintain VSCode extension. So there is no need to edit the readme, I will probably update the extension in the next cq-server release and the instructions about vscode in the cq-server readme will be removed.

**Review by adam-urbanczyk — APPROVED** [review]

**Pull request merged**
