### PR TITLE
Add shape and workplane support to the Workplane.eachpoint() function. Issue #1395

### PR DESCRIPTION
**Pull request by dov**
This PR solves issue #1395 and adds the ability to use the `Workplane.eachpoint()` function with a `Shape` and a `Workplane`.

Here are is an example for using a wire to do a `cutThru()`:

```python
wire = Wire.makeCircle(1, (0, 0, 0), (0, 0, 1))
result = (
    Workplane("XY")
    .box(10, 10, 1)
    .faces(">Z")
    .rect(7, 7, forConstruction=True)
    .vertices()
    .eachpoint(wire)
    .cutThruAll()
)
```

And here is an example for using another workplane, adding a sphere to the center of each face:
```python
box = Workplane().box(2, 2, 2)
sph = Workplane().sphere(1.0)
# Place the sphere in the center of each box face
r = box.faces().eachpoint(sph, combine=True)
```

### CODE REVIEW

**Comment by DovXjet** [comment]
@adam-urbanczyk Ok. I just did. It isn't trivial since the rest of the files are not compliant. 

(However, I just found "darken", which makes it easy).

**Comment by jmwright** [comment]
@dov The following command should show just what is needed to fix your changes. 
```
black --diff --check .
```

**Review by adam-urbanczyk — APPROVED** [review]

**Review by jmwright — APPROVED** [review]
Thanks @dov I just had a couple of corrections to a comment. Otherwise it looks good.

**Comment by jmwright** [comment]
Thanks @dov

**Pull request merged**
