### PR TITLE
dxf splines and ellipse import support

### LINKED ISSUE #373: DXF import spline and ellipse support
Support the following entities:
https://ezdxf.readthedocs.io/en/stable/dxfentities/spline.html#spline
https://ezdxf.readthedocs.io/en/stable/dxfentities/ellipse.html

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Will resolve #373

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@jmwright @dcowden do you have examples of dxf files with splines/rational splines?

**Comment by jmwright** [comment]
@adam-urbanczyk I don't have any at hand, no.

**Comment by adam-urbanczyk** [comment]
I think it is ready. NB: I generated rational spline in ezdxf and imported it for the lack of a better test method. It seems to be working fine, random drawings exported from Inkscape import fine. Not all operations work well for all geometries though (filleting is picky) but I was always able to extrude the solid. Still an experimental feature but I think it is as good as it gets for now.

obraz

**Comment by jmwright** [comment]
Looks good as far as I can tell, thanks!

**Pull request merged**
