### PR TITLE
Pass clean to eachpoint in box, cylinder, interpPlate, sphere, wedge

### LINKED ISSUE #1144: Workplane methods box, cylinder, interpPlate, sphere, wedge do not respect clean parameter
With changes for #1007, selected Workplane methods that had provided a clean parameter, show no change in behavior when setting clean=False.  

AFAIK this was not intentional and clean should be passed on to `eachpoint`.

### PR DESCRIPTION
**Pull request by lorenzncode**
To resolve #1144.

### CODE REVIEW

**Comment by jmwright** [comment]
@lorenzncode Is this ready for review?

**Comment by lorenzncode** [comment]
@jmwright Yes, please review when you get a chance.

**Review by jmwright — APPROVED** [review]
Thanks @lorenzncode

**Review by adam-urbanczyk — APPROVED** [review]

**Comment by adam-urbanczyk** [comment]
Thanks @lorenzncode !

**Pull request merged**
