### PR TITLE
Create a child workplane on a vertex

### LINKED ISSUE #24: Workplane orientation breaks when "Locating workplane on a vertex".
<a href="https://github.com/sander76"></img></a> **Issue by [sander76](https://github.com/sander76)**
_Saturday Aug 11, 2018 at 10:15 GMT_
_Originally opened as https://github.com/dcowden/cadquery/issues/289_

----

Comparable to the example displayed at http://dcowden.github.io/cadquery/examples.html#locating-a-workplane-on-a-vertex I am trying to draw a cilinder on a cube with the center located at one of the cube's vertices. However when I do that the workplane changes orientation unexpectedly.

Two examples below.
1. with cilinder on cube's face at the center
2. identical to above, but now trying to put it at one of the vertices of the cube.

## Example 1

```
import cadquery as cq

result = cq.Workplane("XY").rect(10.0,10.0).extrude(10)

# Draws a cilinder on the center of the XZ face of the cube
result = result.faces("<Y").workplane().circle(2.0).extrude(10)

show_object(result)
```

image

## Example Two

```
import cadquery as cq

result = cq.Workplane("XY").rect(10.0,10.0).extrude(10)

# Should draw the cilinder on the same face as above but with its center placed
# at the lower XZ coordinate of that face
# But instead the workplane orientation changes too.
result = result.faces("<Y").vertices("<XZ").workplane().circle(2.0).extrude(10)

show_object(result)
```

image

### PR DESCRIPTION
**Pull request by ArmoredBlood**
This PR should resolve #24 and #149 (I think).

This is also my first time coding anything in the CAD domain, so I'm open to criticism on the solution since I'm not very familiar with the domain. I have an intermediate level of knowledge of CAD as a hobby user, not as a programmer.

I'm also new to CadQuery, so the only potential issue I see is this only looks at the immediate parent workplane for a Face to use. I'm not sure if it should instead do some kind of recursive search through the entire stack for a Face (assuming there's a long stack of related workplanes)

### CODE REVIEW

**Comment by ArmoredBlood** [comment]
I'm not sure what mypy is wanting from me in the travisCI build. My logic should only be ran when the cq object is a Face.

**Comment by jmwright** [comment]
The mypy stuff is still a mystery to me, but the signature in the lint error matches [CQObject](https://github.com/CadQuery/cadquery/blob/c3e9ef548576186598e82b139b4f11ebbc113a1d/cadquery/cq.py#L60).

So maybe mypy at least thinks you're grabbing the wrong level of object? @adam-urbanczyk will know, I'm sure.

**Review by adam-urbanczyk — APPROVED** [review]

**Comment by adam-urbanczyk** [comment]
Thanks @ArmoredBlood . Mypy does not now that the result of `val()` has the same type between the two calls.

Looks good to me, @jmwright any thoughts?

**Comment by jmwright** [comment]
+1 to merge

**Comment by jmwright** [comment]
Thanks for the contribution @ArmoredBlood

**Pull request merged**
