### PR TITLE
Add "Fixed" to ConstraintKinds type definition

### PR DESCRIPTION
**Pull request by sethfischer**

### CODE REVIEW

**Comment by jmwright** [comment]
@adam-urbanczyk @lorenzncode I feel like you two are best suited to review constraints PRs, so I went ahead and added you both as reviewers on this.

**Review by lorenzncode — COMMENTED** [review]
I'd suggest to add `ConstraintKind` to the imports from `occ_impl.solver` along with the already imported UnaryConstraintKind, BinaryConstraintKind.

**Comment by jmwright** [comment]
@sethfischer It looks like the black lint check is failing.

**Comment by adam-urbanczyk** [comment]
LGTM if CI passes.

**Comment by lorenzncode** [comment]
Thanks @sethfischer!  FYI, the black check requires version 19.10b0.

**Review by lorenzncode — APPROVED** [review]

**Pull request merged**
