### PR TITLE
Add a DOI to the README

### PR DESCRIPTION
**Pull request by adam-urbanczyk**

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
anything against adding this @jmwright ?

**Comment by adam-urbanczyk** [comment]
It is a simple README change, so I'm going ahead with the merge.

**Comment by jmwright** [comment]
@adam-urbanczyk Sorry, been AFK for a lot of the day. I don't really understand what the purpose of the DOI badge is, and I don't get why it seems to be pointing to CQ-editor.

**Comment by adam-urbanczyk** [comment]
Yes, fixed in #412 ... Digital Object Identifier can be used to cite CadQuery in scientific publications. So far I found two. They point to the old repo unfortunately.

**Comment by jmwright** [comment]
Ah, ok. Got it. Thanks for adding this.

**Pull request merged**
