### PR TITLE
Pass exportShape()'s 'tolerance' param to exportStl()

### PR DESCRIPTION
**Pull request by justbuchanan**
For reference, see the freecad_impl version: 

https://github.com/dcowden/cadquery/blob/1c86a979a08fa201283d89ad2848650dbee1009d/cadquery/freecad_impl/exporters.py#L87

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
Looks good. I have one question - is the default tolerance of 0.1 good enough? Did you apply it in practice?

**Comment by jmwright** [comment]
During the design process I usually care more about performance so that I can iterate faster. When I go to export things for printing, CNC, whatever I might then mess with the precision. However, there seems to be a minimum precision to keep models from doing weird things (at least with FreeCAD), and we want to definitely be above that level. So, I guess I would lean towards lower precision and better performance.

**Comment by jmwright** [comment]
@justbuchanan No sorry, I can't remember any specific ones. I remember at some point there was an example, and maybe a test or two that were prone to tolerance issues. The example might have been either the [remote enclosure](https://github.com/dcowden/cadquery/blob/master/examples/FreeCAD/Ex027_Remote_Enclosure.py) or the [panel](https://github.com/dcowden/cadquery/blob/master/examples/FreeCAD/Ex030_Panel_with_Various_Holes_for_Connector_Installation.py), but I can't be certain. There may have been a selector bug mixed in there too.

**Comment by adam-urbanczyk** [comment]
OK, I'll merge as-is then. Everyone agrees?

**Comment by jmwright** [comment]
I think it's fine to merge.

**Pull request merged**
