### PR TITLE
Update assembly constraint docs

### PR DESCRIPTION
**Pull request by lorenzncode**
* Correct FixedPoint constraint example
* Simplify Location usage in examples and format with black for consistency

### CODE REVIEW

**Comment by lorenzncode** [comment]
Fixes #1159.

I removed a note on STEP and transparency.  I find that STEP export includes transparency data so the note may be out of date.

**Comment by jmwright** [comment]
I created a test assembly with transparency and exported to STEP. Then I imported that into the online Autodesk viewer because the version of FreeCAD I'm running doesn't seem to respect the color info. Seems to confirm that transparency works.

Screenshot from 2022-12-23 16-37-08

**Review by jmwright — APPROVED** [review]
Thanks @lorenzncode !

**Comment by lorenzncode** [comment]
@jmwright Thanks for confirming transparency is working for you!  Regarding colors, PR #1157  attempts to resolve an issue with STEP export and color handling.  I've tested STEP export with the PR branch and several viewers, including FreeCAD and Autodesk, and did not find any problem.  You might try exporting the STEP again with the PR 1157 branch to see if it resolves the color issue when viewing in FreeCAD.

**Comment by jmwright** [comment]
@lorenzncode I just tested in FreeCAD 0.20.1 and the color and alpha worked, but I had to turn off the STEP import option `Enable STEP compound merge` which is apparently on by default. If that setting is not turned off I get two default grey merged blocks.

Screenshot from 2022-12-23 18-00-57

**Review by adam-urbanczyk — APPROVED** [review]

**Pull request merged**
