### PR TITLE
Change default polyline and spline behavior

### LINKED ISSUE #147: polyline is not correct, wrong position of first point
Look at the code below:

```
import cadquery as cq
d0 = 17.25
h1 = 25

tri_z_min = 0
tri_O = (4,tri_z_min)
tri_A = (-2*d0,tri_z_min)
tri_B = (tri_A[0],2.25*h1)

tri_plane = cq.Plane( cq.Vector(0,d0,0),cq.Vector(1,0,0),cq.Vector(0,-1,0) )

pts = [ tri_O, tri_A, tri_B ]
cut_block = cq.Workplane(tri_plane).polyline(pts).close().extrude(2*d0)

show_object(cut_block)
```

The prism rightmost edge should have x coordinates equal to 4, but it is 0. It looks like the Workplane coordinate system and the polyline definition have been messed-up.

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
This will resolve #147

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@dcowden @jmwright @yguel I am not sure I'd like to merge this. What are your opinions?

**Comment by yguel** [comment]
Hi Adam,
I did not compile cadquery against your change and had a look at the tests impacted. I will try to find time to do that this week-end.
Anyway, the behavior feels definitely natural now and I think that what it should be.

**Comment by jmwright** [comment]
+1

**Comment by mgreminger** [comment]
I agree that this is a good change that makes polyline more intuitive. The previous behavior of polyline confused me until I figured out that it started at the current point.

**Comment by adam-urbanczyk** [comment]
Alright, let's merge this then. NB: last commit fixes the test coverage.

**Pull request merged**
