### PR TITLE
Docstring and error message fixes

### PR DESCRIPTION
**Pull request by fedorkotov**
- Fixed code examples in AreaNthSelector docstring (previously were not formatted as code blocks).
- Fixed some typos caught with Code Spell Checker VS Code extension

### CODE REVIEW

**Comment by fedorkotov** [comment]
Here is the error from appveyor python 3.6 build (python 3.7 was syccessfull). This is probably not caused by my docstring and comment changes..

```
self = <tests.test_cadquery.TestCadQuery testMethod=testOffset2D>
    def testOffset2D(self):
    
        w1 = Workplane().rect(1, 1).offset2D(0.5, "arc")
        self.assertEqual(w1.edges().size(), 8)
    
        w2 = Workplane().rect(1, 1).offset2D(0.5, "tangent")
        self.assertEqual(w2.edges().size(), 4)
    
        w3 = Workplane().rect(1, 1).offset2D(0.5, "intersection")
        self.assertEqual(w3.edges().size(), 4)
    
>       w4 = Workplane().pushPoints([(0, 0), (0, 5)]).rect(1, 1).offset2D(-0.5)
tests\test_cadquery.py:4081: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cadquery\cq.py:3852: in offset2D
    rv = list(chain.from_iterable(w.offset2D(d, kind) for w in ws))
cadquery\cq.py:3852: in <genexpr>
    rv = list(chain.from_iterable(w.offset2D(d, kind) for w in ws))
cadquery\occ_impl\shapes.py:1802: in offset2D
    obj = downcast(offset.Shape())
cadquery\occ_impl\shapes.py:335: in downcast
    f_downcast: Any = downcast_LUT[shapetype(obj)]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
obj = <OCP.TopoDS.TopoDS_Shape object at 0x000000DE720C5848>
    def shapetype(obj: TopoDS_Shape) -> TopAbs_ShapeEnum:
    
        if obj.IsNull():
>           raise ValueError("Null TopoDS_Shape object")
E           ValueError: Null TopoDS_Shape object
cadquery\occ_impl\shapes.py:325: ValueError
```

**Comment by fedorkotov** [comment]
One of these days I will learn to not trust spellcheckers blindly )

**Comment by jmwright** [comment]
Thanks @fedorkotov !

We were going to remove Python 3.6 from the CI matrix anyway, so that has been done and all the tests pass now.

@marcus7070 @adam-urbanczyk These are straight forward doc fixes, so I'll go ahead and merge without the normal review process.

**Comment by jmwright** [comment]
Thanks @fedorkotov !

We were going to remove Python 3.6 from the CI matrix anyway, so that has been done and all the tests pass now.

@marcus7070 @adam-urbanczyk These are straight forward doc fixes, so I'll go ahead and merge without the normal review process.

**Pull request merged**
