### PR TITLE
Indicate additional breaking changes + docstring fixes

### LINKED ISSUE #572: Helix example is no longer working
This code worked one year ago, it can be found on issue #271. Running the same code today causes `ValueError: Wire or Edge instance required` from the `_sweep` method.

```python
import cadquery as cq

r = 3 # Radius of the helix
p = 1.5 # Pitch of the helix
h = 4 # Height of the helix

# Helix
wire = cq.Wire.makeHelix(pitch=p, height=h, radius=r)
shape = cq.Wire.combine([wire])
helix = cq.Workplane("XY").newObject([shape])

# Final result. A circle sweeped along a helix.
result = (
    cq.Workplane('XZ')
    .center(r, 0)
    .circle(0.1)
    .sweep(helix, isFrenet=True)
)
```

_Tested with the latest CQ version (build with conda from master)_

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Will resolve #572

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
Does the wording look good to you @jmwright ?

**Comment by jmwright** [comment]
@adam-urbanczyk Looks good to me. Is there a specific PR that each breaking change can be tagged with, or is it too hard to pin the changes down to just one PR?

**Comment by adam-urbanczyk** [comment]
Good point, added those.

**Review by jmwright — APPROVED** [review]
Looks good, thanks @adam-urbanczyk

**Comment by adam-urbanczyk** [comment]
OK, merging.

**Pull request merged**
