### PR TITLE
Added quality controls to STEP export for shape and assembly

### PR DESCRIPTION
**Pull request by jmwright**
This is in support of the KiCAD model generator, per #1082 

What is accepted via kwargs can be added to over time, but for now there are just 2 parameters that influence file size.

### CODE REVIEW

**Comment by jmwright** [comment]
@lorenzncode I'm adding tests for the single object and assembly STEP exports, and setting them up to use the temporary directory method you've been using. `test_assembly.test_step_export` worked fine when I added `tmp_path_factory` as an argument, but when I tried the same thing with `test_exporters.testSTEPOptions` I got this error:
```
TypeError: TestExporters.testSTEPOptions() missing 1 required positional argument: 'tmp_path_factory'
```
Am I missing a decorator or something?

**Comment by lorenzncode** [comment]
@jmwright I'd suggest to move the new tests outside of the `TestExporters` class to define as a `pytest` test rather than `unittest`.  `TestExporters` is a subclass of `unittest.TestCase`.

**Review by lorenzncode — APPROVED** [review]
I've tested this branch and confirm file size decrease with write_pcurves False.  I also confirm the uncertainty value change with change in write.precision.mode.

I made some minor changes:

* exporters.export: expose STEP options
* Use default OCCT write.precision.mode value 0
* Doc update

Regarding docstrings, my preference for these export options, would be to defer to OCCT documentation for the most part.  I've modified the docstring to provide short descriptions only, rather than try to reinterpret the meanings especially for write.precision.mode.

**Comment by jmwright** [comment]
@lorenzncode Thanks, these changes look good to me.

**Comment by jmwright** [comment]
@adam-urbanczyk Any objections to me merging this?

**Pull request merged**
