### PR TITLE
Use pytest to run the test suite

### PR DESCRIPTION
**Pull request by Peque**
While creating the test for https://github.com/CadQuery/cadquery/pull/235, I missed a couple of things about `pytest`:

- I had to add extra indentation (tests needed to be inside a class, so extra "boilerplate")
- Output of the test suite was not very pretty

But specially, I had to write:

```python
self.assertAlmostEqual(rotated[0], normal[0])
self.assertAlmostEqual(rotated[1], normal[1])
self.assertAlmostEqual(rotated[2], normal[2])
```

Instead of (`from pytest import approx`):

```python
assert rotated == approx(normal)
```

The latter is definitely shorter, clearer and more Pythonic. :blush:

Also, I think nowadays `pytest` is the *de facto* tool. Or that is my impression.

Hope you like the shift.

### CODE REVIEW

**Comment by jmwright** [comment]
@Peque Thanks for the contributions. The CI systems are complaining about pytest not being installed. I think you'll need to add a pip install line to [appveyor.yml](https://github.com/CadQuery/cadquery/blob/master/appveyor.yml#L22) and [.travis.yml](https://github.com/CadQuery/cadquery/blob/master/.travis.yml#L57) to get those checks to pass.

**Comment by Peque** [comment]
@jmwright You are right! I assumed both Travis and AppVeyor would create the Conda environments with the `environment.yaml` file.

I will fix that. :+1:

**Comment by Peque** [comment]
Also, I forgot about AppVeyor completely. :joy:

**Comment by Peque** [comment]
Had a quick look to try to use `conda env create -f environment.yaml` in both Travis and AppVeyor but:

- It seems you cannot `conda env create -f environment python=other_version` (Conda ignores `other_version`)
- Did not find an easy way to edit the config file with AppVeyor (with Travis it is easy, using `sed` to replace the Python version before creating the virtual environment)

**Comment by Peque** [comment]
@jmwright Passing now.

Isn't the output prettier this way? :heart_eyes: [[before](https://travis-ci.org/CadQuery/cadquery/jobs/624291115?utm_medium=notification&utm_source=github_status) vs. [after](https://travis-ci.org/CadQuery/cadquery/jobs/624314236?utm_medium=notification&utm_source=github_status)]

**Comment by adam-urbanczyk** [comment]
Thanks for the contribution @Peque . Py-test is definitely nicer. Are there any actions required regarding appveyor? BTW there are ways to do sed-like stuff with PowerShell or CMake.

**Comment by Peque** [comment]
@adam-urbanczyk What do you mean by "any actions required regarding appveyor"? I already updated the configuration file (and pipelines are passing).

Yeah, I guessed there would be ways, but I was not willing to spend time on that. :innocent: 

I created this issue, which I think would be the most convenient way to do it: https://github.com/conda/conda/issues/9506

**Comment by jmwright** [comment]
@Peque Looks much nicer, thanks. That will be a nice quality of life improvement for all CadQuery contributors.

@adam-urbanczyk I'm all for merging when you're ready.

**Comment by adam-urbanczyk** [comment]
@Peque ok, clear. I just wasn't sure if you were done with it. Thanks for the contribution!

**Pull request merged**
