### PR TITLE
Warn about upcoming change of the centerOption

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
`centerOption` default value will change from "CenterOfMass" to "ProjectedOirigin"

Related to #202

### CODE REVIEW

**Comment by jmwright** [comment]
I think the code looks good. I do have a few questions.

1. What's the next release that is mentioned in the warning? Does that include RC releases, or just the first stable release?
2. I only get the warning on the first call of `workplane`. I'm assuming this is normal behavior, but I wanted to confirm that, and to make sure that's the intended behavior. I'm fine with it if it is.
3. I get the following output:
```
>>> import cadquery as cq
>>> result = cq.Workplane("XY").workplane().box(1, 1, 1)
/home/jwright/Downloads/repos/cadquery/cadquery/utils.py:21: FutureWarning: Default walue of centerOption will change in next relase to ProjectedOrigin
  FutureWarning,
```
Why does the last `FutureWarning` have a trailing comma? Is there supposed to be more output after that?

**Comment by adam-urbanczyk** [comment]
> I think the code looks good. I do have a few questions.
> 
>     1. What's the next release that is mentioned in the warning? Does that include RC releases, or just the first stable release?

I'd actually propose to release 2.0 soon, and change this in 2.1.

>     2. I only get the warning on the first call of `workplane`. I'm assuming this is normal behavior, but I wanted to confirm that, and to make sure that's the intended behavior. I'm fine with it if it is.

This is your local configuration I think - I cannot reproduce it.

>     3. I get the following output:
> 
> 
> ```
> >>> import cadquery as cq
> >>> result = cq.Workplane("XY").workplane().box(1, 1, 1)
> /home/jwright/Downloads/repos/cadquery/cadquery/utils.py:21: FutureWarning: Default walue of centerOption will change in next relase to ProjectedOrigin
>   FutureWarning,
> ```
> 
> Why does the last `FutureWarning` have a trailing comma? Is there supposed to be more output after that?

I'm afraid this is the default (not so nice) formatting of the warning message showing the line of code where the warnining is invoked. I'd propose to leave as-is.

**Comment by jmwright** [comment]
Sounds good. Do you want to merge, or should I?

**Comment by adam-urbanczyk** [comment]
I'll merge it.

**Pull request merged**
