### PR TITLE
Move to OCCT/OCP 7.5

### LINKED ISSUE #564: Move to OCP 7.5

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Will resolve #564

- [x] Compile OCP 7.5.1
- [x] Fix missing function on Windows
- [x] Generate stubs
- [x] Fix assy crash on CQ-editor (see https://github.com/CadQuery/CQ-editor/pull/238)

### CODE REVIEW

**Comment by jmwright** [comment]
@adam-urbanczyk Lint check shows the following errors.
```
$ mypy cadquery

cadquery/occ_impl/shapes.py:167: error: Module 'OCP.StdPrs' has no attribute 'StdPrs_BRepFont'

cadquery/occ_impl/shapes.py:167: error: Module 'OCP.StdPrs' has no attribute 'StdPrs_BRepTextBuilder'
```

**Comment by adam-urbanczyk** [comment]
That's due to your fix. I'll tag 7.5.1 and pin it here.

**Review by marcus7070 — APPROVED** [review]
Does it matter that we have the stubs for 7.5.1, but the deps refer to 7.5 (7.5.0 I assume)?

I see we have a few tests for text, so that gives some confidence in the text changes.

**Comment by marcus7070** [comment]
> Does it matter that we have the stubs for 7.5.1, but the deps refer to 7.5 (7.5.0 I assume)?

Nevermind, as soon as I hit comment I realised I should have checked the logs, 
```
...
Adding .* to spec 'ocp 7.5' to ensure satisfiability.  Please consider putting {{ var_name }}.* or some relational operator (>/</>=/<=) on this spec in meta.yaml, or if req is also a build req, using {{ pin_compatible() }} jinja2 function instead.  See https://conda.io/docs/user-guide/tasks/build-packages/variants.html#pinning-at-the-variant-level
...
The following NEW packages will be INSTALLED:
...
ocp:                           7.5.1beta-1_py3.8                cadquery  
```

**Review by jmwright — CHANGES_REQUESTED** [review]
Looks good, thanks @adam-urbanczyk 

Since @marcus7070 already approved, I'll go ahead and merge.

**Review by jmwright — APPROVED** [review]

**Comment by marcus7070** [comment]
Thanks so much @adam-urbanczyk, it's awesome that we can follow OCCT's releases so quickly.

**Pull request merged**
