### PR TITLE
Fix screw holes in parametric enclosure example

### PR DESCRIPTION
**Pull request by prplz**
Updates parametric enclosure example for centerOption changes (#532)

### CODE REVIEW

**Comment by prplz** [comment]
I just realized this could also be fixed by skipping workplane entirely: `cutlip.faces(">Z").rect(POSTWIDTH, POSTLENGTH, forConstruction=True).vertices()`

**Comment by jmwright** [comment]
@prplz I think that skipping the `workplane()` call is too likely to cause confusion example. Was this the only `workplane` call that was causing problems, is that why you added `centerOption` to it but none of the others?

**Comment by prplz** [comment]
This particular example needs it because the lid is moved off center, causing the screw holes to not get added without my change

**Review by jmwright — APPROVED** [review]
Ok, thanks for the contribution.

**Comment by jmwright** [comment]
Simple change, merging with only one review.

**Pull request merged**
