### PR TITLE
raise TypeError when Location param is a tuple

### PR DESCRIPTION
**Pull request by RubenRubens**
Let me know if this was what you had on mind @marcus7070.

PR requested on #717 .

### CODE REVIEW

**Comment by fedorkotov** [comment]
(copying my comment from now closed #722)
I don't know for sure if @marcus7070 meant that tuple should be accepted or that exception should be raised when it is passed. But either way I think that `if ... elif ..` chain should end with `else` (not `elif`) which raises an exception when anything of unsupported type is passed.

**Comment by RubenRubens** [comment]
Good point @fedorkotov. I have just choose to end with `elif` because this is tuple specific issue. But it can end with an `else` as you said. Thanks!

**Review by marcus7070 — APPROVED** [review]
Looks good, thanks @RubenRubens!

**Review by jmwright — APPROVED** [review]
Thanks @RubenRubens !

**Pull request merged**
