### PR TITLE
allow specification of dxf layer names to import. for issue #1051

### PR DESCRIPTION
**Pull request by greyltc**

### CODE REVIEW

**Comment by greyltc** [comment]
That check failure is from black.

Shall I `black cadquery` in this PR?
```
black --diff cadquery
...
All done! ✨ 🍰 ✨
10 files would be reformatted, 20 files would be left unchanged.
```

**Comment by adam-urbanczyk** [comment]
> That check failure is from black.
> 
> Shall I `black cadquery` in this PR?
> 
> ```
> black --diff cadquery
> ...
> All done! ✨ 🍰 ✨
> 10 files would be reformatted, 20 files would be left unchanged.
> ```

Please use version specified in https://github.com/CadQuery/cadquery/blob/master/environment.yml

**Comment by adam-urbanczyk** [comment]
@greyltc I fixed the mypy issue. Could you add a test?

**Comment by adam-urbanczyk** [comment]
@greyltc do you plan to work on this PR?

**Comment by lorenzncode** [comment]
I had made part of these changes 2 months ago but at the time the PR didn't appear ready to review so I shelved them.  Anyway it would be good to close the issue (with *squash* I think ideally).

**Review by lorenzncode — APPROVED** [review]

**Review by adam-urbanczyk — APPROVED** [review]

**Comment by adam-urbanczyk** [comment]
LGTM, thanks @greyltc and @lorenzncode !

**Pull request merged**
