### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
WIP 

This PR should solve #12

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
I found some cool applications of cadquery, e.g. :

afbeelding

Real life version:
afbeelding

Taken from: https://jungletools.blogspot.com/

@eddieliberato do you mind if we add your picture to our readme?

**Comment by eddieliberato** [comment]
Hi Adam / Cadquery community,

Yes! you definitely can use the picture and everything. I'm still learning
to code so my code is not so clean and elegant, but you can use everything.
Unfortunately, the last 8 months weren't so good for me, lots of bad things
happened in my personal life, but now everything is passed and hopefully
I'll soon have time to get back to hobby activities like coding / 3d
printing.

I have a few designs that I want to 3d print / machine and test them before
publishing, but I think they'll be interesting as well. I will send an
email after I update my website.

BTW,  you can find other things that I made using Cadquery in my website

https://eddieliberato.github.io/

Also I'd like to say thanks to everybody involved in making this cool
software.
Edi

**Comment by jmwright** [comment]
> lots of bad things happened in my personal life

@eddieliberato Sorry to hear that, but I'm glad it's all passed.

Thanks for sharing you work with the community!

**Comment by dcowden** [comment]
Edi,

I went to your website, and wow. I live the chess set! So cool it's so few
lines of code to make it!

That would make a great addition to the cadquery examples repo for sure!

**Comment by jmwright** [comment]
@adam-urbanczyk Where are we at on updating the README? I seem to remember you saying something about waiting until after the next release.

**Comment by adam-urbanczyk** [comment]
README is on the list of items for CQ2.0 RC. Did not have time yet to finalize this PR. If you feel like you can pick it up.

**Comment by jmwright** [comment]
I left the notification in my inbox to remind me to circle back and this. It will probably be early next week before I can get to it though.

**Comment by jmwright** [comment]
I can't remember why we have a README.txt file that's different than the README.md file. Can I remove that during this update?

**Comment by adam-urbanczyk** [comment]
Yes it can be removed

**Comment by jmwright** [comment]
The readme on the dcowden/cadquery repo was switched to *.rst instead of *.md. Was it decided that wasn't worth the change, or should I do rst here instead?

**Comment by adam-urbanczyk** [comment]
I'm OK with leaving md, but I don't have a strong opinion. If you find rst better go for it.

**Comment by jmwright** [comment]
Which conda install line should go in the readme? The readme on the README-update branch currently has this:
```
conda install -c conda-forge -c cadquery cadquery
```
But users have also been pointed to this line recently:
```
conda install -c cadquery -c conda-forge python=3.6 pythonocc-core=0.18.2 oce=0.18.2 pyparsing
pip install git+https://github.com/CadQuery/cadquery.git
```

**Comment by jmwright** [comment]
@adam-urbanczyk I've pushed the initial draft of the readme. Please leave feedback when you get a chance. We'll need to figure out the question about the conda installation line above, and we'll need to get the new docs deploying to cadquery.github.io/cadquery. Then I can do the final draft of the readme.

**Comment by adam-urbanczyk** [comment]
@jmwright  thanks a lot, I'm going to take a look. Regarding your question, the ambition is to have a conda package so this will eventually work (cf. #59 ):
```
conda install -c conda-forge -c cadquery cadquery
```
Pip version is for getting latest master and possibly doing dev work
```
conda install -c cadquery -c conda-forge python=3.6 pythonocc-core=0.18.2 oce=0.18.2 pyparsing
pip install git+https://github.com/CadQuery/cadquery.git
```

**Comment by adam-urbanczyk** [comment]
@jmwright should I commit to this branch or is it better to open a review?

**Comment by jmwright** [comment]
@adam-urbanczyk I think it's fine to commit to this branch. We'll just have to be careful about merge conflicts, but I'm not doing anything on it right now.

**Comment by adam-urbanczyk** [comment]
I made some adjustments @jmwright , let me know if you agree. If so, I think this can be merged.

Another step towards CQ2.0 RC

**Comment by jmwright** [comment]
@adam-urbanczyk Looks good. We'll still need to get the documentation deployment working correctly, but I can focus on that next. I need to figure out how @dcowden did it on the original repo and get that working here.

**Comment by adam-urbanczyk** [comment]
Isn't read the docs good enough https://cadquery.readthedocs.io/en/latest/ ?

**Comment by jmwright** [comment]
Is that being deployed from our source tree?

**Comment by dcowden** [comment]
the content on https://cadquery.readthedocs.io/en/latest/  seems good enough to me
@jmwright its been a long time, but i think i was using sphinxdoc, and some plugin like travis-sphinx to deploy. I'm not sure that's even the 'right' way any more honestly.

**Pull request merged**
