### PR TITLE
Clean PR for until surface extrude

### PR DESCRIPTION
**Pull request by Jojain**
Trying to remove files from the git history of #782 messed up with my branch.
Hopefully this will be ok (Even though I doubt it seeing the 1k commits coming with it ...)

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@Jojain any reason to close? We'd like to merge it, things just take time...

**Comment by jmwright** [comment]
@Jojain Why is this being closed?

**Comment by Jojain** [comment]
I was thinking of doing the PR from a complete new repo clone to avoid the thousands commits coming with this one since it seemed to be problematic ?

I am actually doing it right now but if you think there is no problem with all the commits then we can reopen this one and merge it when it's time

**Comment by jmwright** [comment]
@Jojain Are you wanting to do more than a git squash?

**Comment by Jojain** [comment]
@jmwright I had no idea of what a git squash was before you just mentionned it. 
From what I've read it imagine it could have help to remove the thousands commits but I have kindof messed up my branch / environmment, so I'm just going to redo a PR and we will call it done. 
Sorry for the disturbance

**Pull request closed without merging**
