### PR TITLE
Fix documentation wording

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Review by jmwright — APPROVED** [review]
Thanks @revolter

**Comment by jmwright** [comment]
@marcus7070 @adam-urbanczyk  I'm trying to spread the load of reviewers here a bit. Let me know if you don't have time to review or if you want to review and weren't tagged.

**Comment by revolter** [comment]
This was displayed as
> You can learn more about selectors Selectors

and now is displayed as
> See Selectors to learn more.

which is also consistent with other sections too.

**Review by marcus7070 — APPROVED** [review]

**Comment by marcus7070** [comment]
Thankyou @revolter! It's great to get this stuff cleaned up!

**Comment by revolter** [comment]
And I love cleaning stuff up ❤️

**Pull request merged**
