### PR TITLE
Fix face and edge geometry LUTs

### LINKED ISSUE #120: edges() is broken with Key Error: 7
For complex shapes one can get
```

/opt/miniconda/envs/pycq/lib/python3.6/site-packages/cadquery/occ_impl/shapes.py in geomType(self)
    298             return tr
    299         else:
--> 300             return geom_LUT_EDGE_FACE[tr(self.wrapped).GetType()]
    301 
    302     def isType(self, obj, strType):  # TODO why here?

KeyError: 7
```

**Issue 1**

Looking into it, I found `geom_LUT_EDGE_FACE` being an interesting mixture of edge and face constants:

```
geom_LUT_EDGE_FACE = \
    {ga.GeomAbs_Arc: 'ARC',
     ga.GeomAbs_Circle: 'CIRCLE',
     ga.GeomAbs_Line: 'LINE',
     ga.GeomAbs_BSplineCurve: 'SPLINE',  # BSpline or Bezier?
     ga.GeomAbs_Plane: 'PLANE',
     ga.GeomAbs_Sphere: 'SPHERE',
     ga.GeomAbs_Cone: 'CONE',
     }
```

leading to

```
import cadquery.occ_impl.shapes as s
s.geom_LUT_EDGE_FACE

{0: 'PLANE', 1: 'CIRCLE', 6: 'SPLINE', 3: 'SPHERE', 2: 'CONE'}
```

Reason being that the constants of edges and faces seem to overlap in occ:

```
import OCC.Core.GeomAbs as ga
print(
    ga.GeomAbs_Arc,
    ga.GeomAbs_Circle,
    ga.GeomAbs_Line,
    ga.GeomAbs_BSplineCurve,
    ga.GeomAbs_Plane,
    ga.GeomAbs_Sphere,
    ga.GeomAbs_Cone,
)

0 1 0 6 0 3 2
```

So 'ARC' == 'LINE' == 'PLANE'

I find it especially strange that `GeomAbs_Arc` and `GeomAbs_Line` overlap.

**Issue 2**
Now
```
print(ga.GeomAbs_OtherCurve)

7
```

Brute force setting 

```
import cadquery.occ_impl.shapes
cadquery.occ_impl.shapes.geom_LUT_EDGE_FACE[7] = "OTHER"
```

makes the `edges()` call work, however, no idea of the side effects.

And due to the overlapping indexes, this part of the code might need some love.

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
WIP - do not merge. This PR will resolve #120

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@bernhard-42 could you check if this PR solves your issue (#120)? It does work for me with the code that you shared:

```python
diam = 5.2
thickness = 2
width = 32
length = 60
gap = 6

xy = cq.Workplane("YX")

base = (xy
    .vLineTo(-length/2  + gap/2, forConstruction=True)
    .hLineTo(-width/2)
    .vLineTo(length / 6)
    .threePointArc((-width*3/8, length*3/8), (-gap/2, length/2))
    .vLineTo((length-gap)/2)
    .hLineTo(0)        
    .mirrorY()
    .extrude(thickness)
    .translate((0, 0, thickness/2))
    .edges("|Z and (not >Y) and (not <Y)").fillet(.7)  # <=== ISSUE
   .edges(">Z or <Z").fillet(0.75)
)
edges = base.edges("not |X")
```

**Comment by bernhard-42** [comment]
Happy to test, however, how do I install the latest version including the fix (which seems is in the branch `adam-urbanczyk-geom-lut-edge-face-fix`)?

**Comment by adam-urbanczyk** [comment]
Take a look here
https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

**Comment by adam-urbanczyk** [comment]
@bernhard-42 exact command would be:

`pip install git+https://github.com/CadQuery/cadquery@adam-urbanczyk-geom-lut-edge-face-fix`

Let me know how it goes!

**Comment by bernhard-42** [comment]
@adam-urbanczyk Thanks for the pip command. Was busy debugging the cq-gui on macos issue ;-)
Now I've tried and it works as expected even on my bigger model (the example above was a simplification).

Unfortunately, it didn't solve another issue (maybe even unrelated):
I get two different types of edges from `BRepAdaptor_Curve(edge)`.
- type 1 is a `Curve` with two vertices
- type 2 is a `CurveOnSurface` with only one vertex
For type 2 the `OCC.Extend.TopologyUtils.discretize_edge` fails. I had hoped that properly handling of the LUT constants would also solve this. But it doesn't. So I currently filter them out (with no visual impact).
Do you know anything about this? Is it related with the `OTHER` type?

**Comment by adam-urbanczyk** [comment]
@bernhard-42 could you paste a full example? I am not sure how to reproduce the issue based on your description.

**Comment by bernhard-42** [comment]
It is the same example as above.

```python
diam = 5.2
thickness = 2
width = 32
length = 60
gap = 6

xy = cq.Workplane("YX")

base = (xy
    .vLineTo(-length/2  + gap/2, forConstruction=True)
    .hLineTo(-width/2)
    .vLineTo(length / 6)
    .threePointArc((-width*3/8, length*3/8), (-gap/2, length/2))
    .vLineTo((length-gap)/2)
    .hLineTo(0)        
    .mirrorY()
    .extrude(thickness)
    .translate((0, 0, thickness/2))
    .edges("|Z and (not >Y) and (not <Y)").fillet(.7)  # <=== ISSUE
   .edges(">Z or <Z").fillet(0.75)
)
```

Let's apply the discretizer:

```python
from OCC.Extend.TopologyUtils import TopologyExplorer, is_edge, discretize_edge

edges = base.edges("|X")
d1 = [discretize_edge(edge.wrapped, 0.05) for edge in edges.objects]
print("d1:", len(d1))

edges = base.edges("not(|X and |Y and |Z)")
d2 = [discretize_edge(edge.wrapped, 0.05) for edge in edges.objects]
print("d2:", len(d2))
```

leads to

```
d1: 16
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-17-8912e2479313> in <module>
      6 
      7 edges = base.edges("not(|X and |Y and |Z)")
----> 8 d2 = [discretize_edge(edge.wrapped, 0.05) for edge in edges.objects]
      9 print("d2:", len(d2))

<ipython-input-17-8912e2479313> in <listcomp>(.0)
      6 
      7 edges = base.edges("not(|X and |Y and |Z)")
----> 8 d2 = [discretize_edge(edge.wrapped, 0.05) for edge in edges.objects]
      9 print("d2:", len(d2))

/opt/miniconda/envs/pycq/lib/python3.6/site-packages/OCC/Extend/TopologyUtils.py in discretize_edge(a_topods_edge, deflection)
    502 
    503     if not discretizer.IsDone():
--> 504         raise AssertionError("Discretizer not done.")
    505     if not discretizer.NbPoints() > 0:
    506         raise AssertionError("Discretizer nb points not > 0.")

AssertionError: Discretizer not done.
```

Let's dig into it:

```python
from OCC.Core.BRepAdaptor import BRepAdaptor_Curve
from OCC.Core.TopLoc import TopLoc_Location
from OCC.Extend.TopologyUtils import discretize_edge, dump_topology_to_string, TopologyExplorer

deflection = 0.01

edges = base.edges("not (|X or |Y or |Z)")
edges2 = [edge.wrapped for edge in edges.objects]
for i, edge in enumerate(edges2):
    curve_adaptator = BRepAdaptor_Curve(edge)
    print(i, curve_adaptator.IsCurveOnSurface(), TopologyExplorer(edge).number_of_vertices())
    try:
        discretize_edge(edge, deflection)
    except:
        print("!! ERROR", i, edge)
```

results in 

```
0 False 2
1 False 2
2 False 2
3 False 2
4 False 2
5 False 2
6 False 2
7 False 2
8 True 1
!! ERROR 8 class<'TopoDS_Edge'; id:2084309009>
9 False 2
10 False 2
11 False 2
12 False 2
13 False 2
14 False 2
15 False 2
16 False 2
17 False 2
18 False 2
19 False 2
20 False 2
21 False 2
22 False 2
23 True 1
!! ERROR 23 class<'TopoDS_Edge'; id:2084309809>
24 False 2
25 False 2
26 False 2
27 False 2
28 False 2
29 True 1
!! ERROR 29 class<'TopoDS_Edge'; id:2084318529>
30 False 2
31 False 2
32 False 2
33 False 2
34 False 2
35 False 2
36 False 2
37 False 2
38 False 2
39 False 2
40 True 1
!! ERROR 40 class<'TopoDS_Edge'; id:2084317665>
41 False 2
42 False 2
43 False 2
44 False 2
45 False 2
46 False 2
47 False 2
```

So, whenever `IsCurveOnSurface` is True and number of vertices is 1, the discretizer fails.
Haven't found a solution up to now, except ignoring these edges.

**Comment by adam-urbanczyk** [comment]
Those seem to be degenerate edges (NB: I put  small cubes to mark their positions):
image

I need to think further if we want to expose them to CQ users via selectors. @jmwright @dcowden any opinions?

Another question is: what are you trying to achieve in the end by using the discretize_edge call? You can maybe check our SVG export routines if this is the direction you are thinking in.

**Comment by adam-urbanczyk** [comment]
@bernhard-42  I changed the behavior to not report degenerated edges when using `edge()` selectors. It should solve your issue. I am still curious what are you up to : ).

**Comment by bernhard-42** [comment]
@adam-urbanczyk Thanks for digging into it and for the visualisation of the degenerated edges.
And thanks for omitting them now. I agree, I don't think, from a cadquery user perspective that they are relevant.

Why do I use discretize_edge? Well, I sometimes struggle with more complex edge and face selectors, so when I decided to completely rewrite my jupyter extension for jupyterlab with pythreejs (https://github.com/bernhard-42/jupyter-cadquery), I added a feature to visualise results of edges() and faces() calls. In order to get edges, I use discretize_edge and then pythreejs thick line geometry to show them. Some artificial plots:
s_9_edges_and_part
s_8_edges
I also added features like transparency, clipping with up to three clipping planes, support of native OCC, ...

**Comment by dcowden** [comment]
Hi, @adam-urbanczyk @bernhard-42 

I'm late to the party-- sorry about that!

If we ever evolved to split the CQ api into a two-layer api, one that are operations, and then another layer on top of that which is fluent ( and presumably matches the current API), then I think the operations api would should provide access to the edges created, modified, and removed.

It is possible that we may want to expose edges created, removed, or deleted for each operation to the user via the CQ api.  It would be incredibly powerful to select edges and faces based on the operation id that created them.  Combined with existing selectors, it would be much easier to chain methods that way.

That's captured as #49,

**Comment by adam-urbanczyk** [comment]
@dcowden  I think what you describe is partially supported by OCC, but it is rather orthogonal the question whether we want to report  degenerated edges to the user. They exist because they are required by the kernel, but IMO have little meaning for typical users.

**Comment by jmwright** [comment]
I would be ok dropping them in the default case since it seems like that will cover most users.

**Comment by adam-urbanczyk** [comment]
@jmwright @dcowden is OK to merge this (after solving the CI issue)?

**Comment by jmwright** [comment]
I'm still not up-to-speed on the Python API yet, but the code looks fine to me. I'm ok with it being merged.

**Comment by dcowden** [comment]
@adam-urbanczyk ok by me

**Comment by adam-urbanczyk** [comment]
PR builds fine so I'm merging. Branch CI fails on build; not sure why that should be even triggered.

**Pull request merged**
