### PR TITLE
Make CadQuery examples browsable in PartCAD

### PR DESCRIPTION
**Pull request by openvmp**

### CODE REVIEW

**Comment by jmwright** [comment]
@openvmp Can you provide more context on your project and how the browsing will work?

**Comment by openvmp** [comment]
@jmwright , PartCAD is growing to become the next gen (or the first real) open source PLM. It supports many ways to define parts and CadQuery is one of them. I want PartCAD users to have easy access to examples how to use CadQuery. I want everyone to, at least, consider switching to the code-CAD approach of defining parts. And CadQuery is one of two (OpenSCAD is the other) most important ones today as that's what published AI models understand well. That's why I want CadQuery examples to be at the fingertips of all PartCAD users. 

This change makes CadQuery examples browsable in the PartCAD Visual Studio Code extension and in https://partcad.org/repository (under '/pub/examples/script/cadquery'). Once the React component is released, it will become possible to host these examples anywhere on the web. I'm not sure how much the latter is valuable to you since you already made the effort to visualize examples in readthedocs and PartCAD can generate markdown but not yet reStructured. However if you want to host the examples elsewhere (or you don't want to build and maintain a CadQuery specific solution that's outside of the core value proposition of CadQuery) then you will be able to use PartCAD for that purpose too.

**Comment by adam-urbanczyk** [comment]
Thanks for the explanation @openvmp . If the other devs are OK, let's merge this. Do you have some ideas on how to keep this updated automatically?

Regarding your visualization component, I don't think it will make the cut. We are using vtk.js and it looks and navigates IMHO better than what you have. You can export assemblies as a vtkjs scenes and embed them in any webpage.

Any additional thoughts @jmwright @lorenzncode ?

**Comment by jmwright** [comment]
@adam-urbanczyk +1 to merge

**Comment by openvmp** [comment]
> Thanks for the explanation @openvmp . If the other devs are OK, let's merge this. Do you have some ideas on how to keep this updated automatically?

If any of CadQuery developers wants to use the PartCAD VSCode extension (do let me know if you use other IDEs to prioritise their support) then you can keep it up to date yourself. If not, PartCAD will point at a specific revision in CadQuery and I will manually move the revision every time I update CadQuery's 'partcad.yaml'. 


> Regarding your visualization component, I don't think it will make the cut. We are using vtk.js and it looks and navigates IMHO better than what you have. You can export assemblies as a vtkjs scenes and embed them in any webpage.

I completely agree with this assessment. You have a complete implementation designed for your needs. I just started building a generic solution for everyone. I will continue improving PartCAD, trying to get closer to what you have and enabling everyone else to get the same faster. Maybe it will make sense for you to use PartCAD for visualisation in the future, maybe not. Your custom solution will help everyone anyway by being a northern star for PartCAD.

**Comment by lorenzncode** [comment]
It looks OK to merge.

Not directly related to this PR... Sketch is not covered in the examples dir or examples.rst.  I'd like to find a way to introduce Sketch somewhere in the examples.  Perhaps start with the "Polygons" doc example (Ex008 in examples dir).  Show the separate Sketch rather than inline form to start with.  Keep the Workplane example but introduce Sketch as an alternative.  

```py
import cadquery as cq

sk1 = (
    cq.Sketch()
    .rect(3.0, 4.0)
    .push([(0, 0.75), (0, -0.75)])
    .regularPolygon(0.5, 6, 90, mode="s")
)

result = cq.Workplane("front").placeSketch(sk1).extrude(0.25)
```

@openvmp  Does your visualization show CQ Sketch objects?

Also you may want to add https://github.com/CadQuery/cadquery-contrib?

**Comment by openvmp** [comment]
> @openvmp Does your visualization show CQ Sketch objects?
It will be supported soon: https://github.com/openvmp/partcad/pull/192

> Also you may want to add https://github.com/CadQuery/cadquery-contrib?
Thanks for the tip. Will do.

**Comment by adam-urbanczyk** [comment]
@lorenzncode  I agree. In general the examples could be "modernized" and extended.

**Comment by adam-urbanczyk** [comment]
Thanks @openvmp !

**Comment by openvmp** [comment]
> > Does your visualization show CQ Sketch objects?
> It will be supported soon: [openvmp/partcad#192](https://github.com/openvmp/partcad/pull/192)
Landed in partcad 0.7.12.

> > Also you may want to add https://github.com/CadQuery/cadquery-contrib?
On it

**Pull request merged**
