### PR TITLE
Allow python versions newer than 3.6

### PR DESCRIPTION
**Pull request by adam-urbanczyk**

### CODE REVIEW

**Comment by johnkgamble** [comment]
@adam-urbanczyk,  does more need to be done on this to merge in? Would be useful to be able to run with 3.7 for me due to dueling requirements. Happy to pitch in if something needs doing.

**Comment by adam-urbanczyk** [comment]
I need to make this work first https://dev.azure.com/cadquery/conda-packages/_build?definitionId=1

**Comment by adam-urbanczyk** [comment]
@johnkgamble almost there. Just need to modify the azure pipeline that builds cq conda packages.

**Comment by adam-urbanczyk** [comment]
Alright everything is green now - merging.

NB: what is still left is to add jobs in the azure pipeline to build the py3.7 version

**Comment by adam-urbanczyk** [comment]
Everything is in place now, azure pipeline with 3.6 and 3.7 is green and packages are uploaded.

**Comment by jmwright** [comment]
Thanks @adam-urbanczyk !

**Pull request merged**
