### PR TITLE
Add support for slicing

### LINKED ISSUE #248: 3D object slicing support
It would be nice to support slicing functionality natively in order to provide high resolution input for CNC machining or 3D printing.

Relevant function
```c++
BRepAlgo_Section::BRepAlgo_Section ( const TopoDS_Shape & Sh,
const gp_Pln &  Pl,
const Standard_Boolean PerformNow = Standard_True
)
```

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
This PR will resolve #248

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
Could you take a look @jmwright ? This is quite simple but I hope will be useful for our users interested in CNC/3D printing. Next logical step would be to add more option for the svg exporter (e.g. orientation control )

**Comment by jmwright** [comment]
@adam-urbanczyk I think it looks ok, but I'd like to spend a little time with it tomorrow before I say for sure. I'll put together a mock project for my CNC router and walk through the steps.

**Comment by jmwright** [comment]
@adam-urbanczyk If I modify the solid at all (like putting in a hole), doing more than one section doesn't seem to work right.
```python
import cadquery as cq

box = cq.Workplane("XY").box(1, 1, 1).faces("Z").workplane().circle(0.2).cutThruAll()

s0 = box.section()
s1 = box.section(0.1)
s2 = box.section(0.2)
s3 = box.section(0.3)
s4 = box.section(0.4)
s5 = box.section(0.5)

show_object(s0)
show_object(s1)
show_object(s2)
show_object(s3)
show_object(s4)
show_object(s5)
```
Screenshot from 2020-05-04 15-05-50

**Comment by adam-urbanczyk** [comment]
I think this is expected - only section s0 contains something. The starting face is already at the top of the solid, so going up results in empty cross-sections:
obraz
If you start from the middle things work as expected:
```python
box = (cq.Workplane("XY").box(1, 1, 1).faces("Z").workplane()
    .circle(0.2).cutThruAll())

show_object(box)

N = 5
for i in range(N+1):
    show_object(box.workplane().section(i*0.1))
```
obraz

**Comment by jmwright** [comment]
I'm wondering if users will expect CQ to automatically figure out the correct way to go to get the layers, similar to how it figures out which way to go when calling "cutThru" on the circle.

**Comment by adam-urbanczyk** [comment]
For a complicated object it is difficult (if not impossible) to guess how you want to slice, same holds for different manufacturing techniques. I think that slicing by default at the current workplane is pretty intuitive, The offset behavior follows what `workplane()` does.

**Comment by jmwright** [comment]
Ok. Feel free to merge, or I will tomorrow sometime.

**Comment by adam-urbanczyk** [comment]
Thanks. We can always extend this functionality in the future. So far I just had to be able to generate a section for laser cutting and this approach worked fine.

**Comment by jmwright** [comment]
Thanks @adam-urbanczyk !

**Pull request merged**
