### PR TITLE
Pipe transition mode fix

### LINKED ISSUE #94: Expose more API of BRepOffsetAPI_MakePipeShell
Specifically allow the user to select transition modes:

afbeelding

Cf. https://opencascade.blogspot.com/2009/12/surface-modeling-part4.html

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
This PR will allow different transition styles for sweeps (see below). I propose to use the leftmost style as the default one.
afbeelding

It will resolve #94 and #39

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@dcowden @jmwright I think it is ready. Maybe additional example would be beneficial too?

**Comment by dcowden** [comment]
the functionality looks great, and i would agree on your choice of default.
I think its necessary to somehow convey what the choices of transition style are, either in the comments, or by changing the api to accept a set of constants.

which kind of brings up a more general question i've always struggled with.  How leaky should we allow our interfaces to be? From a purity viewpoint, we'd want CQ interfaces to be their own, with the idea that it could be in front of any modelling kernel. from that viewpoint, the right decision is to use our own definition for the transition mode, and even to contemplate that perhaps other kernels might allow other options.

on the other hand, from a practical viewpoint, this is based on OCC, and always will be.  You could argue that ultimately, we'll never have other transition modes, becuase you're using MakePipeShell from OCC, and it is what it is. from that viewpoint, we should actually just link to the MakePipeShell documentation, which <presumably> already covers all the details. This makes CQ a leaky abstraction over OCC, but with the benefit that we dont have to re-document and describe many of the underlying operations.

**Comment by adam-urbanczyk** [comment]
I wrote something in the doc strings.  It is not much I have to admit. Ultimately we'd need to extend it (as is the case for other options/methods). Regarding staying OCC agnostic, I'd prefer to be realistic. It is unlikel that it will ever change. I don't even think there exists any other opensource B-Rep CAD kernel at all.

BTW: I came to the conclusion that our doc string format is note very readable. I'll open an issue to discuss if we'd like to change to e.g. nump/scipy format.

**Comment by adam-urbanczyk** [comment]
@dcowden do you think it is good for merging as-is?

**Comment by adam-urbanczyk** [comment]
Merging to keep things going. @dcowden I will open a ticket regarding documentation.

**Pull request merged**
