### PR TITLE
Start building CQ for py3.9

### PR DESCRIPTION
**Pull request by adam-urbanczyk**

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
We might also want to stop providing 3.6 builds

**Comment by jmwright** [comment]
@adam-urbanczyk What's the reasoning behind dropping support for Python 3.6?

**Comment by adam-urbanczyk** [comment]
PEP 563 and shorter build times.

**Review by jmwright — APPROVED** [review]
@adam-urbanczyk The comment I made is just a suggestion. This PR looks good.

**Review by marcus7070 — APPROVED** [review]

**Comment by adam-urbanczyk** [comment]
OK, merging.

**Pull request merged**
