### PR TITLE
Nth selector rounding

### PR DESCRIPTION
**Pull request by cactrot**
I am almost certain that the number of digits to round to for self.TOLERANCE = 0.0001 should be 4 rather than 10000.

### CODE REVIEW

**Comment by cactrot** [comment]
That is weird that most platforms passed, including several versions of windows but not all.

I don't think the test that failed should even depend on DirectionNthSelector

**Comment by adam-urbanczyk** [comment]
Let's see of it reproduces.

**Comment by cactrot** [comment]
The coverage changes it reports are in cq.py and test_cadquery.py. I only edited one line in selectors.py.

https://codecov.io/gh/CadQuery/cadquery/pull/461/changes

It looks like codecov is failing because of other changes happening in the repo.

**Comment by adam-urbanczyk** [comment]
Looks good @cactrot , thanks! Codecov sometimes gives false positives.

**Pull request merged**
