### PR TITLE
Type annotations for shapes

### PR DESCRIPTION
**Pull request by adam-urbanczyk**

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
I think I'm done. Enough of MyPy for quite some time, but I hope it will be beneficial in the long run.

**Comment by adam-urbanczyk** [comment]
One question @jmwright : I fixed `CombinedCenterOfBoundBox` (it was relying on a method that did not exist) but maybe it is better to completely remove it? No one ever complained about it not working so I guess is is effectively dead.

**Comment by jmwright** [comment]
I'd kind of like to keep it. That's because I've implemented versions of something similar in other apps. I don't think I ever knew that it existed in CQ.

**Comment by adam-urbanczyk** [comment]
Alright,  I'll add a test for it then.

**Comment by adam-urbanczyk** [comment]
Done, merging.

**Pull request merged**
