### PR TITLE
Fix Python version info in pip installation instructions

### PR DESCRIPTION
**Pull request by jmwright**
Documentation fix for suggestion in #1462 

Specific comment is [here](https://github.com/CadQuery/cadquery/issues/1462#issuecomment-1866657149).

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
I propose to update to 3.9 for 2.4... This is what meta.yaml states BTW.

**Comment by jmwright** [comment]
@adam-urbanczyk I changed this PR to reference Python 3.9 and newer.

**Review by adam-urbanczyk — APPROVED** [review]
LGTM, thanks!

**Comment by adam-urbanczyk** [comment]
I updated README too

**Comment by jmwright** [comment]
This is straight-forward enough. Merging.

**Comment by adam-urbanczyk** [comment]
Thanks @jmwright !

**Pull request merged**
