### PR TITLE
Temporary fix for 1431 to keep error from propagating

### PR DESCRIPTION
**Pull request by jmwright**

### CODE REVIEW

**Comment by jmwright** [comment]
@adam-urbanczyk @lorenzncode This does not properly fix #1431 , but keeps the error from popping up on other user's systems until the core issue can be fixed.

**Review by adam-urbanczyk — APPROVED** [review]

**Review by lorenzncode — APPROVED** [review]
BTW, I don't see 1.10 on conda-forge at this time.

**Review by lorenzncode — CHANGES_REQUESTED** [review]
I find cadquery fails with multimethod 1.7, 1.8 now.  I'd suggest to change to >=1.9, <1.10  or ==1.9.1.

Example fail with multimethod 1.8:
<details>
$ uname -a
Linux fedora 6.5.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 11 04:07:58 UTC 2023 x86_64 GNU/Linux

$ which python
/usr/bin/python

$ python --version
Python 3.11.6

$ python -m venv ~/tools/venv/testmm1p8

$ . ~/tools/venv/testmm1p8/bin/activate

$ which python
/home/lorenzn/tools/venv/testmm1p8/bin/python

$ which pip
/home/lorenzn/tools/venv/testmm1p8/bin/pip

$ pip install --upgrade pip
Requirement already satisfied: pip in /home/lorenzn/tools/venv/testmm1p8/lib64/python3.11/site-packages (22.3.1)
Collecting pip
  Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Successfully installed pip-23.3.1

$ python -m pip install "cadquery[dev] @ git+https://github.com/CadQuery/cadquery.git" multimethod==1.8
Collecting cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git
  Cloning https://github.com/CadQuery/cadquery.git to /tmp/pip-install-c32ut30p/cadquery_849951219d8d4ba8a832c8740f66170e
  Running command git clone --filter=blob:none --quiet https://github.com/CadQuery/cadquery.git /tmp/pip-install-c32ut30p/cadquery_849951219d8d4ba8a832c8740f66170e
  Resolved https://github.com/CadQuery/cadquery.git to commit 8a9e5a09c92c6506a92eb2cd7365c3e40b8f60a7
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting multimethod==1.8
  Using cached multimethod-1.8-py3-none-any.whl (9.8 kB)
Collecting cadquery-ocp<7.8,>=7.7.0a0 (from cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached cadquery_ocp-7.7.1-cp311-cp311-manylinux_2_35_x86_64.whl.metadata (1.6 kB)
Collecting ezdxf (from cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached ezdxf-1.1.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (72 kB)
Collecting nlopt (from cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached nlopt-2.7.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.0 kB)
Collecting nptyping==2.0.1 (from cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached nptyping-2.0.1-py3-none-any.whl (19 kB)
Collecting typish (from cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached typish-1.9.3-py3-none-any.whl (45 kB)
Collecting casadi (from cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached casadi-3.6.3-cp311-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting path (from cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached path-16.7.1-py3-none-any.whl.metadata (7.5 kB)
Collecting docutils (from cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached docutils-0.20.1-py3-none-any.whl.metadata (2.8 kB)
Collecting ipython (from cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached ipython-8.17.2-py3-none-any.whl.metadata (6.0 kB)
Collecting pytest (from cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached pytest-7.4.3-py3-none-any.whl.metadata (7.9 kB)
Collecting black==19.10b0 (from cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached black-19.10b0-py36-none-any.whl (97 kB)
Collecting click==8.0.4 (from cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached click-8.0.4-py3-none-any.whl (97 kB)
Collecting attrs>=18.1.0 (from black==19.10b0->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting appdirs (from black==19.10b0->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting toml>=0.9.4 (from black==19.10b0->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting typed-ast>=1.4.0 (from black==19.10b0->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached typed_ast-1.5.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting regex (from black==19.10b0->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached regex-2023.10.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
Collecting pathspec<1,>=0.6 (from black==19.10b0->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached pathspec-0.11.2-py3-none-any.whl.metadata (19 kB)
Collecting numpy>=1.20.0 (from nptyping==2.0.1->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached numpy-1.26.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting pyparsing>=2.0.1 (from ezdxf->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached pyparsing-3.1.1-py3-none-any.whl.metadata (5.1 kB)
Collecting typing-extensions>=4.6.0 (from ezdxf->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting fonttools (from ezdxf->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached fonttools-4.44.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (153 kB)
Collecting decorator (from ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting jedi>=0.16 (from ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting matplotlib-inline (from ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 (from ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached prompt_toolkit-3.0.39-py3-none-any.whl.metadata (6.4 kB)
Collecting pygments>=2.4.0 (from ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached Pygments-2.16.1-py3-none-any.whl.metadata (2.5 kB)
Collecting stack-data (from ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached stack_data-0.6.3-py3-none-any.whl.metadata (18 kB)
Collecting traitlets>=5 (from ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached traitlets-5.13.0-py3-none-any.whl.metadata (10 kB)
Collecting pexpect>4.3 (from ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting iniconfig (from pytest->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting packaging (from pytest->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pluggy<2.0,>=0.12 (from pytest->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached pluggy-1.3.0-py3-none-any.whl.metadata (4.3 kB)
Collecting parso<0.9.0,>=0.8.3 (from jedi>=0.16->ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting ptyprocess>=0.5 (from pexpect>4.3->ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached wcwidth-0.2.9-py2.py3-none-any.whl.metadata (14 kB)
Collecting executing>=1.2.0 (from stack-data->ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached executing-2.0.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting asttokens>=2.1.0 (from stack-data->ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting pure-eval (from stack-data->ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting six>=1.12.0 (from asttokens>=2.1.0->stack-data->ipython->cadquery[dev]@ git+https://github.com/CadQuery/cadquery.git)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached cadquery_ocp-7.7.1-cp311-cp311-manylinux_2_35_x86_64.whl (138.2 MB)
Using cached casadi-3.6.3-cp311-none-manylinux2014_x86_64.whl (67.5 MB)
Using cached docutils-0.20.1-py3-none-any.whl (572 kB)
Using cached ezdxf-1.1.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
Using cached ipython-8.17.2-py3-none-any.whl (808 kB)
Using cached nlopt-2.7.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (426 kB)
Using cached path-16.7.1-py3-none-any.whl (25 kB)
Using cached pytest-7.4.3-py3-none-any.whl (325 kB)
Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
Using cached numpy-1.26.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Using cached pathspec-0.11.2-py3-none-any.whl (29 kB)
Using cached pluggy-1.3.0-py3-none-any.whl (18 kB)
Using cached prompt_toolkit-3.0.39-py3-none-any.whl (385 kB)
Using cached Pygments-2.16.1-py3-none-any.whl (1.2 MB)
Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
Using cached traitlets-5.13.0-py3-none-any.whl (84 kB)
Using cached typed_ast-1.5.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (860 kB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Using cached fonttools-4.44.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached regex-2023.10.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (785 kB)
Using cached stack_data-0.6.3-py3-none-any.whl (24 kB)
Using cached asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Using cached executing-2.0.1-py2.py3-none-any.whl (24 kB)
Using cached wcwidth-0.2.9-py2.py3-none-any.whl (102 kB)
Building wheels for collected packages: cadquery
  Building wheel for cadquery (pyproject.toml): started
  Building wheel for cadquery (pyproject.toml): finished with status 'done'
  Created wheel for cadquery: filename=cadquery-2.4.0.dev0-py3-none-any.whl size=150593 sha256=f7a15e64b4fc21bc3567f0a89a4f18c7679e3f5ca964ff5f084fe9e6bb6d7c46
  Stored in directory: /tmp/pip-ephem-wheel-cache-zxd0d_r6/wheels/99/88/1d/66e6fdb5985f2f7c52958d1f9d115ceae55eefbd21f87d0c59
Successfully built cadquery
Installing collected packages: wcwidth, typish, pure-eval, ptyprocess, cadquery-ocp, appdirs, typing-extensions, typed-ast, traitlets, toml, six, regex, pyparsing, pygments, prompt-toolkit, pluggy, pexpect, pathspec, path, parso, packaging, numpy, multimethod, iniconfig, fonttools, executing, docutils, decorator, click, attrs, pytest, nptyping, nlopt, matplotlib-inline, jedi, ezdxf, casadi, black, asttokens, stack-data, cadquery, ipython
Successfully installed appdirs-1.4.4 asttokens-2.4.1 attrs-23.1.0 black-19.10b0 cadquery-2.4.0.dev0 cadquery-ocp-7.7.1 casadi-3.6.3 click-8.0.4 decorator-5.1.1 docutils-0.20.1 executing-2.0.1 ezdxf-1.1.2 fonttools-4.44.0 iniconfig-2.0.0 ipython-8.17.2 jedi-0.19.1 matplotlib-inline-0.1.6 multimethod-1.8 nlopt-2.7.1 nptyping-2.0.1 numpy-1.26.1 packaging-23.2 parso-0.8.3 path-16.7.1 pathspec-0.11.2 pexpect-4.8.0 pluggy-1.3.0 prompt-toolkit-3.0.39 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.16.1 pyparsing-3.1.1 pytest-7.4.3 regex-2023.10.3 six-1.16.0 stack-data-0.6.3 toml-0.10.2 traitlets-5.13.0 typed-ast-1.5.5 typing-extensions-4.8.0 typish-1.9.3 wcwidth-0.2.9

$ pip list
Package           Version
----------------- ----------
appdirs           1.4.4
asttokens         2.4.1
attrs             23.1.0
black             19.10b0
cadquery          2.4.0.dev0
cadquery-ocp      7.7.1
casadi            3.6.3
click             8.0.4
decorator         5.1.1
docutils          0.20.1
executing         2.0.1
ezdxf             1.1.2
fonttools         4.44.0
iniconfig         2.0.0
ipython           8.17.2
jedi              0.19.1
matplotlib-inline 0.1.6
multimethod       1.8
nlopt             2.7.1
nptyping          2.0.1
numpy             1.26.1
packaging         23.2
parso             0.8.3
path              16.7.1
pathspec          0.11.2
pexpect           4.8.0
pip               23.3.1
pluggy            1.3.0
prompt-toolkit    3.0.39
ptyprocess        0.7.0
pure-eval         0.2.2
Pygments          2.16.1
pyparsing         3.1.1
pytest            7.4.3
regex             2023.10.3
setuptools        65.5.1
six               1.16.0
stack-data        0.6.3
toml              0.10.2
traitlets         5.13.0
typed-ast         1.5.5
typing_extensions 4.8.0
typish            1.9.3
wcwidth           0.2.9

$ python -c 'import cadquery; print(cadquery.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lorenzn/tools/venv/testmm1p8/lib64/python3.11/site-packages/cadquery/__init__.py", line 11, in <module>
    from .occ_impl.shapes import (
  File "/home/lorenzn/tools/venv/testmm1p8/lib64/python3.11/site-packages/cadquery/occ_impl/shapes.py", line 2932, in <module>
    class Solid(Shape, Mixin3D):
  File "/home/lorenzn/tools/venv/testmm1p8/lib64/python3.11/site-packages/cadquery/occ_impl/shapes.py", line 3446, in Solid
    @multimethod
     ^^^^^^^^^^^
  File "/home/lorenzn/tools/venv/testmm1p8/lib64/python3.11/site-packages/multimethod/__init__.py", line 218, in __init__
    self[get_types(func)] = func
    ~~~~^^^^^^^^^^^^^^^^^
  File "/home/lorenzn/tools/venv/testmm1p8/lib64/python3.11/site-packages/multimethod/__init__.py", line 279, in __setitem__
    super().__setitem__(types, func)
  File "/home/lorenzn/tools/venv/testmm1p8/lib64/python3.11/site-packages/multimethod/__init__.py", line 81, in __hash__
    return hash(self.__getstate__())
                ^^^^^^^^^^^^^^^^^^^
TypeError: unbound method object.__getstate__() needs an argument


</details>

**Comment by jmwright** [comment]
@lorenzncode I went ahead and pinned to 1.9.1 since we have proven that the issue is not present with that specific version.

**Review by lorenzncode — APPROVED** [review]

**Pull request merged**
