### PR TITLE
Fix a typo.

### PR DESCRIPTION
**Pull request by nirvdrum**

### CODE REVIEW

**Comment by jmwright** [comment]
Thanks for the contribution @nirvdrum !

**Comment by jmwright** [comment]
@adam-urbanczyk Black is failing and saying that 13 files need to be reformatted, even though this PR was a single character change. Was the version of black for the Travis build updated recently or something?

**Comment by adam-urbanczyk** [comment]
Yes, it needs to be pinned to (see #440) :
```
- pip install black==19.10b0
```

**Comment by adam-urbanczyk** [comment]
Thanks @nirvdrum - merging.

**Pull request merged**
