### PR TITLE
Update documentation link

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Use https://cadquery.readthedocs.io/ in the README

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
Forgot about that of course. @dcowden @jmwright are you OK with using read the docs? So far it seems to work quite nicely out of the box and it supports conda

**Comment by jmwright** [comment]
I'm ok with it as long as it's kept in sync with our source tree.

**Comment by adam-urbanczyk** [comment]
It does already https://readthedocs.org/projects/cadquery/builds/

**Comment by dcowden** [comment]
> I'm ok with it as long as it's kept in sync with our source tree.

+1

**Comment by jmwright** [comment]
+1

**Comment by adam-urbanczyk** [comment]
Alright, merging

**Pull request merged**
