### PR TITLE
Fix union with None

### LINKED ISSUE #1536: Workplane.union error with None
I use the following instead of `union`:

```python
import cadquery as cq
cq.Workplane.union2 = lambda self, x: x is None and self or self.union(x)
```
This avoids a `ValueError: Cannot union type '<class 'NoneType'>'`. `cq.Workplane().union(None)` makes that exception. The type hint says that union(None) should work.

I use it to share code for two similar parts:
```python
def mkresult(withBase=True):
    return (cq.Workplane("XY").circle(68).extrude(2)
        .union2(withBase and base or None)
        ....
```

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Closes #1536

### CODE REVIEW

**Comment by michaelgale** [comment]
Wow!  Really grateful that this has finally been changed.  I can't tell you how much boilerplate code I've written to handle the inevitable union to "None" scenario when making composite solids/geometries from iteration.

**Comment by adam-urbanczyk** [comment]
Thanks @michaelgale ! Was there something stopping you from opening an issue or PR? Or did we miss it somehow?

**Comment by michaelgale** [comment]
> Thanks @michaelgale ! Was there something stopping you from opening an issue or PR? Or did we miss it somehow?

I am somewhat hesitant to suggest changes to a mature core API since these types of changes can have unpredictable consequences for other users.  Since this issue didn't represent a bug or unexpected behaviour, I didn't think to ever raise a PR or issue.  Since CQ is so easily extended with plugins, I tend to rely on this mechanism to introduce syntactic shortcuts and convenience functions to streamline my integrations with CQ.  In future, I might lower my threshold for raising issues and/or contributing changes with a PR.  Thanks again to the CQ team for maintaining this project.

**Review by lorenzncode — APPROVED** [review]
Hey just one comment regarding boilerplate.  This behavior results in additional parents which may be different than current boilerplate.  As @michaelgale mentions iteration, I suppose it depends on size of the iteration or sparseness whether there is any significant noticeable impact.


```py
import cadquery as cq

r0 = cq.Workplane().cylinder(1, 10)

for i in range(1, 101):
    if i == 50:
        obj = cq.Workplane().box(1, 1, 10)
    else:
        obj = None

    r0 = r0.union(obj)
```

image

**Comment by adam-urbanczyk** [comment]
@lorenzncode I'm not sure that I understand. Currently union with `None` results in an error.

**Comment by jmwright** [comment]
Looks good, thanks @adam-urbanczyk

**Comment by lorenzncode** [comment]
@adam-urbanczyk  Right, I'm only pointing out that skipping `union` to avoid the error is not *exactly* the same as this fix. 

In #1536 , `union2` is defined to avoid the error by skipping the call to `union`.  

In the PR branch, calling `union` with `None` extends the Workplane chain and does not result in error.  

The result at the end of the chain is the same in either case only that the length of the chain is different.

**Comment by adam-urbanczyk** [comment]
> @adam-urbanczyk Right, I'm only pointing out that skipping `union` to avoid the error is not _exactly_ the same as this fix.
> 
> In #1536 , `union2` is defined to avoid the error by skipping the call to `union`.

That is the intention, `.union()` will in general union items on the stack, so creating a new object is desired. Shall I merge?

**Comment by lorenzncode** [comment]
That makes sense to me.  +1 to merge.  Thanks @adam-urbanczyk

**Pull request merged**
