### PR TITLE
Add Tuple support to CQGI

### LINKED ISSUE #1370: CQGI does not recognize VectorLike tuple as InputParameter
```py
l = 1
w = 2
h = 3
o = (2, 2, 0)

result = cq.Workplane(origin=o).box(l, w, h, False)

show_object(result)
```
`l`,`w`,`h` are reported as parameters after parse.   `o` is not.

### PR DESCRIPTION
**Pull request by jmwright**
Closes #1370 

Missing Tuple support was mentioned in [this commit](https://github.com/CadQuery/cadquery/pull/1367/commits/57d815a6ac8db983237627a060124c1e9d49468e). @lorenzncode Are there changes that need to be made in this PR to recapture your original intent from #1367 ?

### CODE REVIEW

**Comment by lorenzncode** [comment]
@jmwright I'm new to CQGI.  I expected the default value of the parameter to match the value of the script.

```py
model = cqgi.parse(user_script)
params = model.metadata.parameters
for p, v in params.items():
    print(v.name, v.default_value)
```

I get 'pnt (0, 0, 0)' instead of 'pnt (0.5, 0.5, 0.5)'  

`user_script` is the example from the assy docs: https://github.com/CadQuery/cadquery/blob/76dbeef63007d40e7a2003a444552ceeeb1367ad/doc/assy.rst?plain=1#L786

**Comment by jmwright** [comment]
@lorenzncode That should be fixed now.

**Comment by lorenzncode** [comment]
Thanks @jmwright.  Should tuples of arbitrary length be supported?  Say I have a parameter used with `pushPoints` or Sketch `push`.

**Comment by jmwright** [comment]
@lorenzncode Tuples of varying length are supported now.

**Comment by lorenzncode** [comment]
@jmwright I tried another tuple case with CQGI.

```py
import cadquery as cq

pts = ((0, 0), (0, 10))
result = cq.Workplane().pushPoints(pts).box(1, 2, 3, False)

show_object(result)
```

This results in ```Unable to handle assignment for variable 'pts'```.

**Comment by jmwright** [comment]
@lorenzncode How much tuple nesting should we allow?

**Comment by lorenzncode** [comment]
@jmwright  A few thoughts on the CQGI input parameter issue:   


1. Extend the CQGI supported types to include additional commonly used types. 

   It's difficult to predict what might be commonly used such as the tuple nesting level.  Perhaps the new types would be something like:

   - 'VectorLike type':  as in geom.py line 28 
   - 'Sequence of points type' Along the lines of the `pushPoints` argument type: Iterable[Union[VectorLike, Location]]
   

   - pros:
     - Straighforward for CQGI to validate input parameters 

   - cons: 
     - User script must conform to the supported input parameter types

       Say my script defines a sequence of float, string pairs.  I can try to redefine the script to use the CQGI types, else I am out of luck.  


2. (or) Provide a mechanism to define custom input parameter types 

   - pros:
     - More flexibility in defining input parameters

   - cons:
     - I assume it might require additional boilerplate?

**Comment by adam-urbanczyk** [comment]
@lorenzncode are you actually using it? Maybe it is not the best thing to work on in terms of ROI?

**Comment by lorenzncode** [comment]
@adam-urbanczyk  No, I'm not.  Agree, this was hypothetical based on my understanding of the purpose of CQGI.

**Comment by jmwright** [comment]
@lorenzncode My suggestion would be that we move your thoughts above into another CQGI issue, and I'll see about supporting a tuple of (vector-like) tuples via the ast.tuple class.

**Comment by jmwright** [comment]
@lorenzncode @adam-urbanczyk This PR does not have all the extra features mentioned above, but it seems work solve the immediate problem of CQGI not handling tuples at all. Please review when you have time.

**Review by lorenzncode — APPROVED** [review]
Thanks @jmwright.  Here is a friendly reminder to squash if you end up doing the merge.

**Review by adam-urbanczyk — APPROVED** [review]

**Pull request merged**
