### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by tkoyama010**
Fix a small typo.

### CODE REVIEW

**Review by lorenzncode — COMMENTED** [review]
While we're at it, what about the following?:
L99 "lets step through it"
L159 "lets break it down a bit"

The subsection capitalization is inconsistent in this seciton.  In some cases title case is used and others sentence case.  The capitalization is wrong either way of "A" in the line directly above this change.
"Start With A single, simple Plate"

For the subsections, I'd suggest:
Prerequisites: conda + CQ-editor running from an environment  (no change)
What we'll accomplish (no change)
Start with a single, simple plate
Add the holes
More holes
... no change to remaining subsection titles.

**Comment by adam-urbanczyk** [comment]
Should I just merge this PR, or are you still working on it?

**Comment by tkoyama010** [comment]
Sorry for the late reply. It is ready for merge.

**Review by lorenzncode — APPROVED** [review]
Thanks for addressing all instances of the typo in the file.

**Review by adam-urbanczyk — APPROVED** [review]

**Comment by adam-urbanczyk** [comment]
Thanks @tkoyama010 !

**Pull request merged**
