### PR TITLE
Assembly hierarchy - 2nd take

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
This PR solves nested assembly naming and enforces unique names on a single assembly level.

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
CC: @bernhard-42

**Review by jmwright — APPROVED** [review]

**Comment by jmwright** [comment]
Looks ok to me. Thanks.

**Comment by adam-urbanczyk** [comment]
@bernhard-42 do you agree with merging this for now? Based on the discussion in #543 you have some design choices to be made that might take some time.

**Comment by bernhard-42** [comment]
@adam-urbanczyk fine for me. I do have a plan forward. Thanks for adding the hierarchies and the `__classes__`  thing

**Comment by adam-urbanczyk** [comment]
OK, I'll merge tomorrow.

**Pull request merged**
