### PR TITLE
Boolean operation syntactic sugar

### PR DESCRIPTION
**Pull request by RubenRubens**

### CODE REVIEW

**Comment by marcus7070** [comment]
It might be worth mentioning in the docs that with `r = a + b`, `r.parent == a` and r has the same CQContext object as a.

Or perhaps just state `r = a + b` is equivalent to `r = a.union(b)`.

**Comment by jmwright** [comment]
@RubenRubens It looks like the lint check is failing.

**Comment by RubenRubens** [comment]
I think it's OK now. Thanks for the helpful comments.

**Comment by RubenRubens** [comment]
There is disscussion in #568 about which operators we should include. Suming up, there are multiple options but... is this the way to go?

+ Union: `|`
+ Cut: `-`
+ Intersection `&`

I'm happy with it and hopefully @adam-urbanczyk would be too. 😄

**Comment by adam-urbanczyk** [comment]
I think I'd still add `+` as an alternative to `|`. What do you think @jmwright ?

**Comment by jmwright** [comment]
> I think I'd still add + as an alternative to |.

+1

**Comment by marcus7070** [comment]
Sphinx doesn't autosummary dunder methods (except `__init__`), so these new methods don't appear in the HTML docs at all. Relevant stackoverflow: https://stackoverflow.com/questions/62142793/autosummary-generated-documentation-missing-all-dunder-methods-except-for-ini 

Looks easier to just write a section manually than to make sphinx autosummary do what we want.

Linking to #493.

**Comment by jmwright** [comment]
There's also this that shows up just after the lint check.
```
$ mypy cadquery
cadquery/cq.py:3772: error: Unsupported left operand type for + ("Type[Workplane]")
Found 1 error in 1 file (checked 24 source files)
The command "mypy cadquery" exited with 1.
```

**Comment by adam-urbanczyk** [comment]
Yes, MyPy does not like monkey patching. Will fix it.

**Review by adam-urbanczyk — APPROVED** [review]

**Comment by adam-urbanczyk** [comment]
@jmwright looks ready to me. Codecov complains about a docstring line...

**Comment by jmwright** [comment]
Ok, merging.

**Review by jmwright — APPROVED** [review]

**Pull request merged**
