### PR TITLE
Add Black formatting check to CI

### PR DESCRIPTION
**Pull request by Peque**

### CODE REVIEW

**Comment by jmwright** [comment]
@Peque With this check added to CI, if the lint check fails, the user will need to run `black` on their local copy of the code, correct? We'll need to document that for contributors.

**Comment by Peque** [comment]
@jmwright Good idea! :blush: 

I added this in the `README.md` file: 6e730151a296969382a8f3655d2ff9e534b9b156

Also, rebased against upstream after the latest changes by Bruno.

**Comment by Peque** [comment]
@jmwright I could also add a recommendation to use `--fixup` when commiting changes to the pull request after review (like [I did here for example](https://github.com/CadQuery/cadquery/pull/243)), to then finally autosquash everything before merging the changes. But maybe that is not what you are used to...

**Comment by jmwright** [comment]
@Peque Yes, that's a very different workflow from what I'm used to. I don't know enough to really understand what that would do to the commit tree.

**Comment by Peque** [comment]
Maybe I should also add that adding assertions to the test is a must?

It seems the latest changes integrated (in particular the `test_assembleEdges` test in `test_cadquery.py`) do not have any assertions.

**Comment by Peque** [comment]
@jmwright If you are curious:

- https://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html
- https://www.mikulskibartosz.name/git-fixup-explained/

**Comment by Peque** [comment]
@jmwright Updated the guidelines with: 34db27c99eb304bcfcce594ad68f1b598a063fc3

**Comment by Peque** [comment]
@adam-urbanczyk Any thoughts on this? :blush:

**Comment by adam-urbanczyk** [comment]
@Peque cf. my comment above. Otherwise I am wondering if it would be possible to add a pre-commit hook to streamline using black. Do you happen to have any experience in doing that? This https://pre-commit.com/ looks like a relevant solution.

**Comment by Peque** [comment]
@adam-urbanczyk Rebased and force-pushed. Emoji were removed. :broken_heart: 

No experience with pre-commit hooks, sorry. I personally don't like that very much. I am more in favor of: your computer, your rules. You decide when to run those checks and how. As long as your changes pass the pipelines, you are fine. Maybe if I spent some time trying them I would change my mind, but I have not been encouraged too much to try them so far.

**Comment by Peque** [comment]
@adam-urbanczyk Friendly ping. :blush:

**Comment by adam-urbanczyk** [comment]
Looks good @Peque , @jmwright are you OK with merging this?

**Comment by jmwright** [comment]
@adam-urbanczyk Yes, +1

**Comment by adam-urbanczyk** [comment]
Thanks again for the contribution @Peque  !

**Pull request merged**
