### PR TITLE
add the choice to not import all dxf layers

### PR DESCRIPTION
**Pull request by greyltc**
this is especially useful for ignoring layers in drawings containing note text or dimensions

### CODE REVIEW

**Comment by jmwright** [comment]
Looks like a good to me, thanks @greyltc 

@adam-urbanczyk Any objections to merging if all the tests pass?

**Comment by adam-urbanczyk** [comment]
Please don't merge yet - I'll have some comments.

**Comment by jmwright** [comment]
@adam-urbanczyk Ok

@greyltc Looks like the black lint check failed. That's a new-ish thing that's been added to CI. Let me know if you want an explanation.

**Comment by adam-urbanczyk** [comment]
OK, I changed the naming slightly (I'd like to eventually add an `include` parameter) and excluded layers are not parsed now. Are you willing to add a test for this functionality @greyltc ? If not, I'm OK with merging as-is.

**Comment by greyltc** [comment]
Yeah, I can test!

**Comment by greyltc** [comment]
I think this is ready to be merged. The travis issues giving the red x there are not related to this pr.

**Comment by adam-urbanczyk** [comment]
All green - merging. Thanks @greyltc !

**Pull request merged**
