### PR TITLE
.workplane docstring update

### PR DESCRIPTION
**Pull request by adam-urbanczyk**

### CODE REVIEW

**Comment by adam-trhon** [comment]
@adam-urbanczyk hello, please also check the quick start manual, section "More Holes", line 10, point 2 (it says that "The center point of a workplane on a face is always at the center of the face, which works well here")

**Comment by marcus7070** [comment]
Looks good to me!

**Comment by jmwright** [comment]
I'm re-running two CI checks that seem to have failed for no reason.

**Review by jmwright — APPROVED** [review]

**Comment by adam-trhon** [comment]
@jmwright If I understand the quoted sentence right, it refers to the previous defualt (which was `CenterOfMass`), not the current default. Namely the "center point of a workplane on a face is **always** at the center of the face" part. It think it should be changed to "center point of a workplane on a face is at the center of the face **in this case**".

**Comment by adam-urbanczyk** [comment]
@adam-trhon @jmwright I removed the confusing line completely. Do you think that the tutorial remains clear?

**Comment by jmwright** [comment]
+1

**Comment by adam-urbanczyk** [comment]
Alright, merging.

**Pull request merged**
