### PR TITLE
Add Ex025 for sweeping a wire along a helix from cq.Wire.makeHelix()

### PR DESCRIPTION
**Pull request by daemacles**
This adds an example for essentially extruding a 2D wire shape along a helix.

### CODE REVIEW

**Comment by jmwright** [comment]
@daemacles Thanks for writing this up. It looks like the lint check is failing. Can you take a look at that?

**Comment by jmwright** [comment]
@daemacles Thanks for writing this up. It looks like the lint check is failing. Can you take a look at that?

**Comment by daemacles** [comment]
Will do.

**Comment by jmwright** [comment]
Thanks @daemacles !

**Pull request merged**
