### PR TITLE
OCP 7.7.1

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Use latest OCCT

### CODE REVIEW

**Review by jmwright — APPROVED** [review]
I think this looks fine, thanks @adam-urbanczyk 

I'll get a beta PyPI package of cadquery-ocp 7.7.1 published after these changes are merged.

**Comment by lorenzncode** [comment]
I see that pytest passed in azure.  When I test locally I get pytest failures (user error or actual issue?).

```
$ conda list "python_abi|cadquery|ocp|occt"
# packages in environment at /home/lorenzn/tools/mambaforge_230715/envs/ocp771:
#
# Name                    Version                   Build  Channel
cadquery                  2.4.0.dev0                dev_0    <develop>
occt                      7.7.1           all_h16763a6_201    conda-forge
ocp                       7.7.1.0         py310ha643c62_1    conda-forge
ocp-stubs                 7.7.0                    pypi_0    pypi
python_abi                3.10                    3_cp310    conda-forge
```

partial pytest output
```
$ pytest tests/test_assembly.py -k test_colors_fused_assy --disable-warnings --sw
...
>                       if ctool.GetColor_s(
                            child, XCAFDoc_ColorType.XCAFDoc_ColorGen, color_subshape
                        ) or ctool.GetColor(
                            child, XCAFDoc_ColorType.XCAFDoc_ColorSurf, color_subshape
                        ):
E                       TypeError: GetColor_s(): incompatible function arguments. The following argument types are supported:
E                           1. (L: OCP.TDF.TDF_Label, type: OCP.XCAFDoc.XCAFDoc_ColorType, colorL: OCP.TDF.TDF_Label) -> bool
E                       
E                       Invoked with: <OCP.TDF.TDF_Label object at 0x7fd27035cf30>, <XCAFDoc_ColorType.XCAFDoc_ColorGen: 0>, <OCP.Quantity.Quantity_ColorRGBA object at 0x7fd26f939af0>

tests/test_assembly.py:399: TypeError
======================================================================================= short test summary info ========================================================================================
FAILED tests/test_assembly.py::test_colors_fused_assy[empty_top_assy-expected0] - TypeError: GetColor_s(): incompatible function arguments. The following argument types are supported:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: Test failed, continuing from this test next run. !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 failed, 68 deselected, 7 warnings in 1.12s =============================================================================
```

**Comment by adam-urbanczyk** [comment]
Are you sure you are using the corect version of the tests? Both azure and appveyor pass.

**Comment by adam-urbanczyk** [comment]
e.g. I cannot find `or ctool.GetColor(`, in this PR.

**Comment by lorenzncode** [comment]
No, I did not have the correct version of the tests.   Still I reproduced the test failure after updating to the PR branch.

After debug I found the pip package cadquery-ocp was installed in my conda env.  I had not expected that and not sure how it got installed in my env.  The tests now pass after removing the pip package.

**Comment by adam-urbanczyk** [comment]
Alright, shall we merge then?

**Comment by jmwright** [comment]
> Alright, shall we merge then?

+1

**Review by lorenzncode — APPROVED** [review]
Yes, please go ahead.  Thanks!

**Pull request merged**
