### PR TITLE
Add support for closed path fillet to Wire.fillet()

### PR DESCRIPTION
**Pull request by dov**
This PR adds support for fillet of a closed wire to the `Wire.fillet()` method, by adding a fillet arc between the last and the first segments

### CODE REVIEW

**Review by adam-urbanczyk — APPROVED** [review]
LGTM, thanks!

**Comment by adam-urbanczyk** [comment]
@jmwright will you take a look? I had to replace some uses of `typing_extensions.Literal` with `typing.Literal` because of a unrelated osx failure. I do not fully understand why, but in general it is a change for better.

**Review by jmwright — APPROVED** [review]
+1 to merge

**Comment by adam-urbanczyk** [comment]
Thanks @dov !

**Pull request merged**
