### PR TITLE
Fix inconsistent examples code style

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by jmwright** [comment]
@revolter Is this ready to review?

**Comment by revolter** [comment]
Yes yes 🤞🏻

**Review by jmwright — APPROVED** [review]
These are whitespace changes consistent with what a lint checker would require. I'm going to go ahead and merge.

Thanks @revolter

**Comment by revolter** [comment]
Exactly, but I did them manually, because I was on the train, and I also find it relaxing 😂

**Comment by jmwright** [comment]
@revolter Sounds good. I was partly also letting the other devs know that I was going to merge this without following our normal 2-dev-review rule since it was a straight-forward change and is standards compliant. You may see us do that on other doc changes. Thanks for taking the time to do this.

**Comment by revolter** [comment]
I'm happy that you found them helpful too and I didn't break anything 😁

**Pull request merged**
