### PR TITLE
Svg update

### PR DESCRIPTION
**Pull request by jmwright**
PRs #1277 and #1325 are both open with SVG export changes, but neither one fixed this issue for me. There was an extra bottom-right margin that I could not remove in the resulting SVG, and I wanted my SVGs to fill the image edge to edge for my use case while still respecting the top/left margins. These changes accomplish that.

Below are before and after examples.

Before:
Screenshot from 2023-06-14 21-38-18

After:
Screenshot from 2023-06-14 21-36-17

### CODE REVIEW

**Review by adam-urbanczyk — APPROVED** [review]
Thanks, LGTM. I assume that the black border in the "after" picture is some artifact not coming from CQ.

**Comment by jmwright** [comment]
> I assume that the black border in the "after" picture is some artifact not coming from CQ.

Correct. I must have gotten part of the frame of the app when I did the screenshot.

**Review by lorenzncode — COMMENTED** [review]
I'd like to propose the following changes:

1. Explicitly choose to recompute width *or* height. 

   - With the current PR the user does not know ahead of time which dimension will be recomputed.

     I get surprised to find either one of width/height changed. 
     
   - It is more straightforward to specify a fixed width or height.  The user will likely have one in mind and does not need to specify both since the other is recomputed. 

     I can then say I want a width of 200 pixels and the height fits automatically.


2.  The current PR handling of margin is inconsistent with fitView=False.  I suggest to respect the width or height value given - do not change it according to margin (margin padded to inside of width and height).


Please see these changes here: 
https://github.com/lorenzncode/cadquery/commit/6aab3be7f46bcd5e2529724c2fb00c1e67c7d180


The fitView option was removed.  Instead, you can fit by specifying -1 for one of the dimensions.

This results in a width of 200, height is computed:
```py
width = 200
height = -1 
```

This results in a height of 100, width is computed:
```py
width = -1 
height = 100 
```

**Comment by jmwright** [comment]
@lorenzncode I've made those changes (except for the documentation changes), but I'm not convinced that using `-1` for autofit is the best way. Maybe we should allow the user to leave out the other dimension from `opts` or set it to `None`.

**Comment by adam-urbanczyk** [comment]
None sounds more pythonic

**Review by lorenzncode — APPROVED** [review]
Looks good, thanks @jmwright!

**Comment by jmwright** [comment]
@adam-urbanczyk It looks like AppVeyor is grabbing the OCP 7.7.1 pre-release and it might be breaking the builds.

```
TypeError: GetColor(): incompatible function arguments. The following argument types are supported:
```

**Comment by adam-urbanczyk** [comment]
Should be solved, I moved 7.7.1 to dev

**Comment by adam-urbanczyk** [comment]
Hm, not quite. Seems that 7.7.1 is available from the conda-forge channel even though the PR is not merged.

**Pull request merged**
