### PR TITLE
Initial implementation of cq.Shape selectors

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
- [x] Implementation
- [x] Tests
- [x] Docs
- [ ] ~~Refactor - move more stuff to shape (?)~~

### CODE REVIEW

**Comment by jmwright** [comment]
@adam-urbanczyk This PR is still marked as draft. Is this an interim review, or a final review? All the tests are in place and pass, so I wondered if maybe the intent was to take the PR out of draft.

**Comment by adam-urbanczyk** [comment]
> @adam-urbanczyk This PR is still marked as draft. Is this an interim review, or a final review? All the tests are in place and pass, so I wondered if maybe the intent was to take the PR out of draft.

I forgot to undraft it.

**Review by jmwright — APPROVED** [review]
Things seem to work well as far as I can tell. Thanks @adam-urbanczyk !

**Review by lorenzncode — APPROVED** [review]
I did some testing with the PR branch and did not find any issue.  Thanks @adam-urbanczyk !

**Pull request merged**
