### PR TITLE
Surface modeling functionality

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
- [x] additional inputs for nsided
- [x] thicken
- [x] deprecate interplate
- [x] project
- [x] construct face on geometry
- [x] tests
- [ ] docs

### CODE REVIEW

**Comment by bragostin** [comment]
@adam-urbanczyk  in Opencascade doc 
https://dev.opencascade.org/doc/refman/html/class_b_rep_offset___make_offset.html
`GeomAbs_JoinType = GeomAbs_Arc`
seems to be the default.

**Review by lorenzncode — APPROVED** [review]
Yes it looks like quite a lot of useful functionality worth merging including `project`, `makeNSidedSurface` enhancements, face `thicken`, `distance`, `distances`, allow `VectorLike` everywhere.

It might make sense to add `thicken` as a method of class `Shell` as well.


I found one problem when testing the `VectorLike` changes.  The problem is specific to CQ-editor when the _Reload CQ_ option is enabled.  The following raises a `DispatchError` on the second Render in CQ-editor.

```
wire0 = cq.Workplane().lineTo(5, 5).lineTo(10, 0).close().val()
#r = cq.Solid.extrudeLinear(cq.Face.makeFromWires(wire0), (0, 0, 1))
r = cq.Solid.extrudeLinear(cq.Face.makeFromWires(wire0), cq.Vector(0, 0, 1))
```

The exception is handled in `cqmultimethod` but then the wrong `extrudeLinear` method is called.

**Review by jmwright — APPROVED** [review]
Thanks @adam-urbanczyk !

**Comment by adam-urbanczyk** [comment]
Alright, shall I merge @jmwright @lorenzncode ?

**Comment by lorenzncode** [comment]
Yes, +1 for merging.  The CQ-editor issue can be looked into separately.  Thanks!

**Comment by jmwright** [comment]
+1 for merging

**Pull request merged**
