### PR TITLE
Drop Python 3.6 and add 3.8 to AppVeyor

### PR DESCRIPTION
**Pull request by marcus7070**

### CODE REVIEW

**Comment by marcus7070** [comment]
@adam-urbanczyk, was this missed in #672? Or did you not want to move to VS2019 image?

**Comment by adam-urbanczyk** [comment]
It was just missed

**Review by adam-urbanczyk — APPROVED** [review]

**Comment by adam-urbanczyk** [comment]
I also adjusted travis for the sake of completeness

**Review by jmwright — APPROVED** [review]
Thanks @adam-urbanczyk

**Pull request merged**
