### PR TITLE
Remove import STEP form URL

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
This code is not compatible with py3 and not covered by any tests. Any thoughts?

### CODE REVIEW

**Comment by jmwright** [comment]
I feel like @dcowden added this in at some point for testing or demo purposes, but I can't remember any details and may be mistaken.

**Comment by adam-urbanczyk** [comment]
If it is needed I can refactor, but as-is it is not py3 compatible.

**Comment by dcowden** [comment]
This code supported the original www.parametricparts.com site, where you could load models shared by others via url.  Its ok to dump it for now, its not hard to re-add later

**Comment by adam-urbanczyk** [comment]
OK, I'll remove for now. If needed in the future I propose to use requests over urllib

**Comment by dcowden** [comment]
Agreed!

**Pull request merged**
